/**
 * Italian (it) editorial translation of the post bodies in
 * `src/content/blog.ts` (the module-private POST_BODIES map).
 * Staging only. Register: Lei (courtesy) + impersonal editorial voice.
 * Byline: "Il team di Ptah Tours".
 * Keys, `kind`, `publishedISO` and `readMinutes` are mirrored 1:1.
 */
import type { BlogPostMeta } from "@/content/blog";

export const postBodiesIt: Record<string, BlogPostMeta> = {
  "cairo-beyond-the-guidebook": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-03-12",
    readMinutes: 6,
    body: [
      { kind: "p", text: "Il Cairo travolge chi lo visita per la prima volta, e questo fa parte del suo fascino. Oltre venti milioni di persone, un fiume più antico della storia e un traffico che trasforma un tragitto di due miglia in un'avventura. La guida turistica La manderà alle piramidi e al Museo Egizio — e senza dubbio dovrebbe andarci — ma il Cairo che amiamo è quello che si scopre nelle ore intermedie." },
      { kind: "h2", text: "Mangi dove mangiano i cairoti" },
      { kind: "p", text: "Il koshari è la città in un piatto: riso, lenticchie, pasta, ceci, cipolla fritta croccante e una salsa di pomodoro all'aglio, assemblato in fretta e mangiato in piedi. Lasci perdere i caffè turistici e segua invece la fila degli impiegati all'ora di pranzo. Il koshari migliore è rumoroso, economico e servito con una bottiglietta di salsa piccante da trattare con rispetto." },
      { kind: "p", text: "Al calare della sera, i vecchi forni di fatir e i carretti di ful e taameya danno il meglio di sé. Il cibo di strada egiziano è tra i più appaganti della regione, e mangiarlo bene è soprattutto questione di andare dove c'è movimento e si cucina al momento." },
      { kind: "h2", text: "Trovi il tramonto" },
      { kind: "p", text: "Tutti fotografano le piramidi al tramonto. Meno gente sale alla Cittadella di Saladino, dove la Moschea di Muhammad Ali corona il profilo della città e l'intera metropoli si distende in basso nella luce dorata e radente. Quando il richiamo alla preghiera si leva sopra i tetti, è una delle grandi esperienze gratuite del Cairo." },
      { kind: "h2", text: "Le sale tranquille del museo" },
      { kind: "p", text: "Le celebri sale del Museo Egizio sono imperdibili, ma le sale in fondo ripagano la pazienza: vetrine di oggetti quotidiani — sandali, pettini, giocattoli per bambini, la tavolozza di uno scriba — che rendono il mondo antico all'improvviso, e in modo commovente, umano. Le nostre guide adorano questi angoli, e una mattinata senza fretta qui vale più di un'ora affannata in qualsiasi momento." },
      { kind: "p", text: "Il Cairo non si concede facilmente. Gli dedichi qualche giorno, una buona guida e un buon appetito, e diventerà la città in cui vorrà tornare." },
    ],
  },
  "karnak-sound-and-light": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-04-02",
    readMinutes: 5,
    body: [
      { kind: "p", text: "Lo spettacolo di luci e suoni di Karnak ha una reputazione, non sempre benevola. Alcuni viaggiatori lo liquidano come una messa in scena teatrale datata. Fatto bene — e con i tempi giusti — è una delle serate più suggestive che possa vivere a Luxor." },
      { kind: "h2", text: "Il momento è tutto" },
      { kind: "p", text: "Il segreto sta nell'affluenza. Programmiamo le visite in modo che, mentre lo spettacolo avanza attraverso il tempio, i nostri viaggiatori raggiungano la Grande Sala Ipostila quando è quasi vuota. Stare in piedi tra 134 colonne colossali nell'oscurità, illuminate sezione dopo sezione, con la narrazione che risuona su una pietra di tremila anni: è questo il momento che la gente ricorda." },
      { kind: "h2", text: "Ciò che l'illuminazione fa bene" },
      { kind: "p", text: "Qualunque cosa si pensi del testo, il progetto illuminotecnico comprende l'architettura. Osservi come gli obelischi catturano la luce e sembrano innalzarsi; come un bagno di colore riveli una parete di geroglifici davanti alla quale di giorno sarebbe passato oltre. Karnak fu costruito per mettere in scena il dramma del divino, e al calare della notte continua a farlo." },
      { kind: "h2", text: "Lo abbini a una visita diurna" },
      { kind: "p", text: "Lo spettacolo funziona meglio come seconda visita. Veda prima Karnak alla luce del giorno — si orienti, lasci che la Sua guida Le mostri i faraoni che vi lasciarono il segno nell'arco di duemila anni — e torni poi di notte per sentirlo anziché studiarlo. Di giorno si comprende Karnak; di notte si intuisce perché contò tanto." },
    ],
  },
  "alexandria-mediterranean-soul": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-04-20",
    readMinutes: 6,
    body: [
      { kind: "p", text: "A due ore a nord del Cairo, l'Egitto cambia idea. La luce del deserto si stempera in foschia marina, il caffè si fa più forte e una brezza salmastra arriva dal Mediterraneo. Alessandria ha sempre guardato verso l'esterno — alla Grecia, a Roma, al mare aperto — e ancora oggi sembra un altro Paese che sventola la stessa bandiera." },
      { kind: "h2", text: "Cominci in riva all'acqua" },
      { kind: "p", text: "La Corniche è il salotto della città. La percorra nel tardo pomeriggio, quando la luce fa d'argento il mare e i pescatori ritirano le lenze, e capirà ogni alessandrino malinconico che abbia mai conosciuto. La curva della baia verso la cittadella è una delle grandi passeggiate urbane dell'Egitto." },
      { kind: "h2", text: "La biblioteca, antica e nuova" },
      { kind: "p", text: "L'antica Biblioteca di Alessandria è scomparsa da tempo, ma la sua erede moderna — la Bibliotheca Alexandrina — è un edificio imponente che merita bene un'ora, un'eco voluta del ruolo della città come luogo del sapere. Ricorda che la storia di Alessandria riguarda tanto le idee quanto i monumenti." },
      { kind: "h2", text: "Scendere nelle catacombe" },
      { kind: "p", text: "Le Catacombe di Kom el-Shoqafa sono il tesoro più singolare della città: un complesso funerario di epoca romana su più livelli che sprofonda a spirale sottoterra, dove gli stili egizio, greco e romano si fondono sulle stesse pareti scolpite. In nessun altro luogo si coglie così pienamente l'identità meticcia e mediterranea di Alessandria." },
      { kind: "h2", text: "E il pesce" },
      { kind: "p", text: "Concluda al mercato del pesce, dove sceglie il Suo pescato e glielo cucinano in modo semplice e superbo. Pesce alla griglia, una spruzzata di limone, pane e insalate, e il mare a pochi metri: è questo il pasto che fa tornare la gente a casa decisa a ripartire." },
    ],
  },
  "red-sea-reef-etiquette": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-05-08",
    readMinutes: 5,
    body: [
      { kind: "p", text: "Le barriere coralline del Mar Rosso sono tra le più sane e belle al mondo, e mantenerle tali dipende in parte da chi le visita. Un buon snorkeling non riguarda solo ciò che vede, ma la leggerezza con cui vi si muove. Ecco come lo fanno le nostre guide subacquee." },
      { kind: "h2", text: "Padroneggi il proprio assetto" },
      { kind: "p", text: "La cosa più importante che possa fare per una barriera è non toccarla. Una pinneggiata che solleva sabbia, una mano che si appoggia al corallo: i piccoli contatti sommano danni reali nell'arco di migliaia di visitatori. Resti orizzontale, con le pinne alte e all'indietro, e galleggi anziché mettere i piedi. Se è alle prime armi, lo dica alla Sua guida; La aiuterà a trovare l'equilibrio prima in acque basse." },
      { kind: "h2", text: "Non dia mai da mangiare ai pesci" },
      { kind: "p", text: "È allettante, ed è dannoso. Nutrirli altera il comportamento dei pesci, sconvolge il delicato equilibrio della barriera e abitua gli animali alle persone in modi che per loro non finiscono bene. Su ogni barca Ptah la regola è semplice: guardare, non nutrire." },
      { kind: "h2", text: "La protezione solare conta" },
      { kind: "p", text: "Molte protezioni solari comuni contengono sostanze che danneggiano il corallo. Chiediamo a tutti di usare una crema solare minerale e sicura per i coralli; o, meglio ancora, di coprirsi con una maglia in lycra e lasciare che sia il tessuto a fare il lavoro. Ciò che mette sulla pelle finisce nell'acqua." },
      { kind: "h2", text: "Dove trovare acque tranquille" },
      { kind: "p", text: "I siti famosi lo sono per un motivo, ma si affollano. Vicino a Sharm, in particolare, ci sono barriere più tranquille dove condividerà l'acqua con quasi nessuno; le nostre guide le conoscono, e sanno come programmare un'uscita per avere la barriera più per Lei. Una barriera più quieta è una barriera migliore, per Lei e per essa." },
    ],
  },
  "slow-nile-felucca-days": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-05-24",
    readMinutes: 4,
    body: [
      { kind: "p", text: "Si può vedere moltissimo dell'Egitto a tutta velocità — tempio dopo tempio, tomba dopo tomba, spuntando meraviglie. Ma alcune delle ore migliori del viaggio arrivano quando si smette di provare a vedere qualsiasi cosa. La prima fra tutte: un pomeriggio in feluca." },
      { kind: "h2", text: "Senza motore, senza orario" },
      { kind: "p", text: "La feluca è una tradizionale barca a vela di legno, mossa solo dal vento e dalla perizia. Non c'è motore a incalzarla né rotta fissa oltre a dove consente la brezza. Ad Assuan, dove il Nilo è al suo più bello — isole, massi di granito, barche a vela bianca contro il deserto — è questo il modo di stare sull'acqua." },
      { kind: "h2", text: "Il ritmo del fiume" },
      { kind: "p", text: "Si accomodi tra i cuscini, lasci una mano a sfiorare l'acqua e permetta al capitano di fare ciò che le feluche fanno qui da secoli. Compare un thermos di tè caldo e zuccherato. Gli uccelli lavorano lungo le rive. La luce si fa dorata. La conversazione rallenta, poi si ferma, e a nessuno importa." },
      { kind: "h2", text: "Perché lo includiamo" },
      { kind: "p", text: "Potremmo riempire quel pomeriggio con un altro sito. Scegliamo di non farlo. Una tranquilla traversata in feluca è il contrappeso di un itinerario intenso: il momento che lascia sedimentare tutto ciò che si è visto, e il ricordo che affiora per primo quando, mesi dopo, la gente descrive il proprio viaggio. L'Egitto premia il viaggiatore che ogni tanto non fa nulla, splendidamente." },
    ],
  },
  "best-time-to-visit-egypt": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-09-15",
    readMinutes: 7,
    body: [
      { kind: "p", text: "Non esiste un unico momento migliore per visitare l'Egitto, solo il momento migliore per il viaggio che ha in mente. Gli inverni freschi si addicono ai templi e alle tombe; i mesi di mezza stagione barattano un po' di caldo con meno gente e prezzi migliori; e perfino la piena estate ha le sue ricompense se si pianifica attorno al sole. Ecco come si presenta davvero l'anno sul posto." },
      { kind: "h2", text: "Inverno (da novembre a febbraio): la stagione classica" },
      { kind: "p", text: "È alta stagione, e a ragione. Le giornate sono calde e limpide, le serate fresche, e percorrere i siti all'aperto di Giza, Luxor e Assuan è davvero piacevole. Il rovescio della medaglia è la compagnia: i siti famosi sono ora più affollati, e i prezzi di crociere e hotel toccano il massimo. Prenoti in anticipo, inizi le giornate di visite all'orario di apertura, e l'unico vero inconveniente della stagione quasi svanisce." },
      { kind: "h2", text: "Primavera e autunno (marzo, aprile, ottobre): il punto ideale" },
      { kind: "p", text: "I mesi di mezza stagione sono il nostro discreto favorito. Il clima resta mite, la gente diminuisce e i prezzi migliorano nettamente. La primavera porta con sé un avvertimento: il khamsin, un vento caldo e polveroso che può levarsi per un giorno o due tra marzo e maggio. Passa in fretta, e una mattinata flessibile lo aggira senza problemi. Per la maggior parte dei viaggiatori, queste settimane sono l'equilibrio migliore in assoluto." },
      { kind: "h2", text: "Estate (da maggio a settembre): calda, economica e più tranquilla di quanto pensi" },
      { kind: "p", text: "L'estate nell'Alto Egitto è davvero calda, e non fingeremo il contrario. Ma è anche il periodo più economico e con meno gente per viaggiare, ed è del tutto sostenibile con il ritmo giusto: visiti all'alba, riposi durante le ore feroci del mezzogiorno e riparta quando la giornata si rinfresca. Una crociera sul Nilo, con il ponte all'ombra e la brezza del fiume, è un modo particolarmente astuto di vedere il sud in estate." },
      { kind: "h2", text: "Per il Mar Rosso" },
      { kind: "p", text: "La costa segue il proprio calendario. Hurghada, Sharm El Sheikh e Marsa Alam sono calde e adatte alla balneazione tutto l'anno, con l'acqua più calda da giugno a ottobre. Anche l'inverno è gradevole per le immersioni e lo snorkeling, solo con una muta e qualche giornata di vento. Se lo scopo del Suo viaggio è la spiaggia, va bene quasi qualsiasi mese." },
      { kind: "h2", text: "Allora, quando dovrebbe andare?" },
      { kind: "p", text: "Vada in inverno per il clima più comodo per le visite. Vada nella mezza stagione di primavera o autunno per il miglior equilibrio complessivo tra clima, costo e tranquillità. Vada in estate se ciò che conta di più è il budget, o se è diretto al Mar Rosso. Qualunque cosa scelga, adattiamo il ritmo quotidiano alla stagione; ed è questo, più del calendario, a far sentire un viaggio senza sforzo." },
    ],
  },
  "first-time-nile-cruise": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-08-28",
    readMinutes: 7,
    body: [
      { kind: "p", text: "Una crociera sul Nilo è il modo più antico di vedere l'Egitto e ancora il migliore. Per qualche giorno è il fiume a viaggiare per Lei: i templi arrivano sulla riva, il paesaggio scorre oltre il ponte e la logistica che rende estenuante un viaggio via terra semplicemente si dissolve. Se non ne ha mai fatta una, ecco cosa aspettarsi." },
      { kind: "h2", text: "Il ritmo quotidiano" },
      { kind: "p", text: "La vita a bordo si assesta su uno schema semplice. Le prime ore del mattino sono per i grandi siti, prima del caldo e della folla; le ore centrali per navigare, pranzare e il ponte al sole; il tardo pomeriggio porta un altro tempio o un tratto tranquillo sull'acqua. I pasti sono di solito a buffet e abbondanti, le serate rilassate, e tutto ciò Le chiede ben poco oltre a presentarsi e contemplare." },
      { kind: "h2", text: "Quale direzione, e per quanto tempo" },
      { kind: "p", text: "La maggior parte delle crociere va tra Luxor e Assuan, e le opzioni consuete sono di tre o quattro notti. Navigare verso sud da Luxor o verso nord da Assuan tocca gli stessi grandi siti — Karnak e la Valle dei Re dal lato di Luxor, Edfu e Kom Ombo nel mezzo, Philae vicino ad Assuan — quindi scelga in base alla città da cui preferisce arrivare e ripartire in aereo. Quattro notti danno a tutto un po' più di respiro." },
      { kind: "h2", text: "Nave da crociera o dahabiya?" },
      { kind: "p", text: "Le grandi navi del fiume sono comode e conviviali, con piscine, più ponti e qualche centinaio di compagni di viaggio. Una dahabiya è l'alternativa intima: una piccola barca a vela con una manciata di cabine, senza ressa e con un ritmo più pacato, mosso dal vento, più vicino a come il fiume è sempre stato navigato. Le navi si addicono a chi ama comfort e compagnia; le dahabiye a chi cerca quiete e romanticismo. Nessuna delle due scelte è sbagliata." },
      { kind: "h2", text: "Scegliere la cabina" },
      { kind: "p", text: "Spenda un po' di più per un ponte più alto e una finestra o un balcone come si deve, se può: la vista è l'essenziale, e passerà a contemplarla più tempo di quanto immagini. Le cabine sono di solito compatte ma ben curate; non ci starà molto." },
      { kind: "h2", text: "Qualche consiglio sincero" },
      { kind: "p", text: "Porti uno strato leggero per le serate ventose sul ponte e un buon cappello per il giorno. Le mance vengono di solito raccolte per l'equipaggio e gestite alla fine; chieda alla Sua guida cosa è consuetudine. E resista alla tentazione di riempire l'itinerario: le ore di navigazione, quando nulla è in programma e la valle scorre accanto, sono quelle che ricorderà di più." },
    ],
  },
  "seven-days-in-egypt": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-08-10",
    readMinutes: 8,
    body: [
      { kind: "p", text: "Sette giorni sono la misura giusta per un primo viaggio in Egitto: sufficienti per vedere bene Il Cairo, Luxor e Assuan, e abbastanza brevi da rientrare in una vacanza normale. Il segreto di una settimana che risulti piena e non frenetica è sapere cosa tralasciare. Ecco l'itinerario classico che operiamo, giorno per giorno, e le rinunce che vi stanno dietro." },
      { kind: "h2", text: "Giorni 1–2: Il Cairo e Giza" },
      { kind: "p", text: "Atterri al Cairo e si immerga del tutto. Le piramidi di Giza e la Sfinge sono l'ovvia prima mattina, idealmente abbinate al Grande Museo Egizio, le cui gallerie riuniscono ora i tesori in un unico luogo straordinario. Il secondo giorno è per la piramide a gradoni di Saqqara e le rovine di Menfi, e poi per l'intrico del Cairo islamico e copto — moschee, chiese, il bazar di Khan el-Khalili — alla ricerca della città viva dietro i monumenti." },
      { kind: "h2", text: "Giorno 3: volo verso sud, a Luxor" },
      { kind: "p", text: "Un breve volo interno risparmia un lungo tragitto su strada e La lascia nella maggiore concentrazione di siti antichi della Terra. Cominci con calma dalla riva orientale: Karnak, vasto e stratificato, e il tempio di Luxor, che si vede meglio quando la sera si rinfresca e si accendono i riflettori." },
      { kind: "h2", text: "Giorni 4–6: il Nilo, da Luxor ad Assuan" },
      { kind: "p", text: "Sono il cuore del viaggio, quasi sempre a bordo di una crociera. La riva occidentale di Luxor porta la Valle dei Re e il tempio a terrazze di Hatshepsut. Navigando verso sud, farà scalo a Edfu e Kom Ombo, due dei templi meglio conservati esistenti, prima di raggiungere Assuan per vedere Philae e una tranquilla traversata in feluca tra le sue isole. Il ritmo di tempio, fiume, tempio è l'essenza dell'Egitto." },
      { kind: "h2", text: "Giorno 7: Abu Simbel o un finale rilassato" },
      { kind: "p", text: "I più appassionati possono aggiungere un'uscita all'alba verso Abu Simbel, i colossali templi rupestri di Ramses II sulle rive del lago Nasser: indimenticabili, ma con levataccia. L'alternativa è una mattinata più tranquilla ad Assuan e un rientro senza fretta. In ogni caso, sette giorni sono un insieme appagante, non un campionario affannato." },
      { kind: "h2", text: "Le rinunce che facciamo" },
      { kind: "p", text: "Voliamo tra Il Cairo e il sud anziché guidare, evitiamo di aggiungere un soggiorno balneare sul Mar Rosso che si mangerebbe due giorni, e includiamo di proposito ore pacate — la feluca, un pranzo senza fretta — perché i momenti salienti abbiano spazio per sedimentare. Una settimana a misura d'uomo vale più di dieci giorni vissuti nella nebbia." },
      { kind: "h2", text: "Vuole più tempo?" },
      { kind: "p", text: "Con dieci giorni o due settimane aggiungiamo Alessandria, più Mar Rosso o le oasi del Deserto Occidentale. Ma se ha una settimana, questo itinerario ne trae il massimo." },
    ],
  },
  "what-to-pack-for-egypt": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-07-22",
    readMinutes: 6,
    body: [
      { kind: "p", text: "Fare le valigie per l'Egitto si riduce a tre fatti: il sole è forte, i siti e le moschee richiedono un po' di sobrietà, e il deserto si rinfresca sorprendentemente al calare della sera. Azzecchi questo e potrà viaggiare leggero. Ecco la lista essenziale che conta davvero, e ciò che chi parte per la prima volta tende a portare in eccesso." },
      { kind: "h2", text: "Abbigliamento: leggero, ampio e a strati" },
      { kind: "p", text: "Pensi a cotone e lino traspiranti in tinte chiare, di taglio ampio per tenerLa fresco e riparare la pelle dal sole. Gli strati contano più di quanto immagini: le mattine sull'acqua e le sere nel deserto possono essere davvero fredde, quindi porti un maglione o una giacca leggera anche in estate. Il capo più utile che quasi tutti dimenticano è una sciarpa o uno scialle grande: protezione dal sole, riparo dalla polvere, una copertura per le sere fresche e una copertura sobria per le moschee, tutto in uno." },
      { kind: "h2", text: "Come vestirsi per i siti e le moschee" },
      { kind: "p", text: "L'Egitto è informale, ma coprire spalle e ginocchia è rispettoso nei templi ed è atteso nelle moschee, sia per gli uomini sia per le donne. Le donne dovrebbero portare una sciarpa per coprirsi i capelli entrando in una moschea. Nessuno deve vestirsi con abiti pesanti: basta puntare al sobrio e traspirante anziché al troppo succinto, e si sentirà a proprio agio ovunque." },
      { kind: "h2", text: "Calzature" },
      { kind: "p", text: "Camminerà molto più di quanto si aspetti, su sabbia, pietra irregolare e qualche ripida rampa di tomba. Un paio di scarpe da camminata chiuse e già rodate è l'unica cosa che meriti priorità; i sandali vanno bene per il tempo libero, ma proteggono male tra detriti e terreno rovente." },
      { kind: "h2", text: "Kit sole e salute" },
      { kind: "p", text: "Un cappello a tesa larga, buoni occhiali da sole e una protezione solare alta e sicura per i coralli sono irrinunciabili. Porti eventuali farmaci personali nella confezione originale, una piccola scorta di sali reidratanti e una borraccia riutilizzabile: mantenersi idratati è la migliore difesa contro il caldo. Il gel per le mani e qualche fazzoletto si guadagnano anch'essi un posto." },
      { kind: "h2", text: "Cosa lasciare a casa" },
      { kind: "p", text: "I più portano semplicemente troppo; ripeterà volentieri gli stessi strati leggeri. Lasci a casa gli abiti pesanti «per ogni evenienza», e lasci il drone: farlo volare in Egitto è molto limitato e può causare seri problemi ai siti. Faccia la valigia per il viaggio che davvero farà, non per tutti i viaggi che riesce a immaginare." },
    ],
  },
  "beyond-giza-underrated-sites": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-07-05",
    readMinutes: 7,
    body: [
      { kind: "p", text: "Le piramidi di Giza si guadagnano la loro fama, e ogni primo viaggio dovrebbe includerle. Ma il paesaggio antico dell'Egitto va molto più a fondo delle sue tre pietre più celebri, e alcuni dei siti più appaganti sono quelli dove si vede a malapena un altro visitatore. Una volta visti gli emblemi, ecco dove andare poi." },
      { kind: "h2", text: "Saqqara e Dahshur" },
      { kind: "p", text: "A mezz'ora a sud di Giza, Saqqara ospita la Piramide a Gradoni di Djoser, la più antica grande struttura in pietra al mondo e, in un senso molto concreto, il luogo dove ebbe inizio la costruzione delle piramidi. Poco oltre, a Dahshur, si ergono la Piramide Romboidale e la Piramide Rossa, la prima autentica piramide a facce lisce mai completata. Insieme raccontano la storia che Giza si limita a concludere, e spesso può esplorarle in quasi totale solitudine." },
      { kind: "h2", text: "Abido e Dendera" },
      { kind: "p", text: "Questi due templi ripagano il tragitto più lungo a nord di Luxor. Abido conserva gli squisiti rilievi scolpiti di Seti I e la celebre Lista Reale, un elenco di faraoni che risale alla leggenda. Dendera, dedicato alla dea Hathor, custodisce uno dei soffitti dipinti meglio conservati dell'Egitto, con i suoi blu profondi e le sue stelle dorate ancora vividi lassù. Poche escursioni concentrano tanta bellezza per così poca gente." },
      { kind: "h2", text: "Kom Ombo ed Edfu" },
      { kind: "p", text: "Visti di solito da una crociera sul Nilo, questi due meritano una menzione a parte. Kom Ombo è un raro tempio doppio, dedicato a due divinità insieme, con una parete di strumenti chirurgici scolpiti che non smette mai di stupire. Edfu, dedicato a Horus, è il grande tempio conservato più integralmente del Paese: lo percorra e capirà che aspetto avessero questi luoghi quando erano intatti." },
      { kind: "h2", text: "Il Deserto Occidentale" },
      { kind: "p", text: "Per i viaggiatori con più tempo, le oasi del Deserto Occidentale — Bahariya, Dakhla, Kharga — e le surreali formazioni di gesso scolpite dal vento del Deserto Bianco offrono un Egitto in cui non c'è quasi nessun altro: sorgenti, palmeti e calde notti nel deserto sotto cieli immensi. È un viaggio del tutto diverso, e indimenticabile." },
      { kind: "h2", text: "Perché andare oltre gli emblemi" },
      { kind: "p", text: "I siti famosi Le dicono cosa realizzò l'antico Egitto. Quelli più tranquilli Le permettono di sentirlo: da solo in una sala dipinta, con il custode, la Sua guida e tremila anni di silenzio. È questo l'Egitto di cui ci si innamora, e comincia appena oltre il bordo della cartolina." },
    ],
  },
  "egypt-with-kids-family-guide": {
    author: "Il team di Ptah Tours",
    publishedISO: "2026-06-18",
    readMinutes: 7,
    body: [
      { kind: "p", text: "L'Egitto è uno dei grandi viaggi da fare con i bambini. La storia che conoscono a metà dai cartoni animati e dai libri di testo diventa reale davanti a loro — mummie vere, piramidi vere, cammelli e barche e tesori — e il senso di meraviglia è contagioso. Richiede un po' di pianificazione per riuscire bene, ed ecco cosa abbiamo imparato." },
      { kind: "h2", text: "È più adatto ai bambini di quanto pensi" },
      { kind: "p", text: "Gli egiziani adorano i bambini, e le famiglie sono accolte con calore ovunque, dai mercati animati ai templi tranquilli. I bambini ricevono spesso più pazienza e più sorrisi degli adulti. Si dà il caso che le grandi attrazioni del Paese siano proprio quelle che accendono le giovani immaginazioni: piramidi da guardare in alto, tombe in cui sbirciare, un fiume da navigare." },
      { kind: "h2", text: "Ritmo ed età" },
      { kind: "p", text: "L'unica regola che salva un viaggio in famiglia è andare più piano. Due siti al giorno sono più che sufficienti; un programma serrato sfinisce tutti. I bambini in età scolare — dai sei anni circa in su — sono di solito quelli che ne traggono di più, abbastanza grandi da ricordare le piramidi e seguire una storia. I più piccoli possono venire senza problemi; basta inserire pomeriggi in piscina e tempo di riposo, e ridimensionare di conseguenza le ambizioni di visita." },
      { kind: "h2", text: "Battere il caldo" },
      { kind: "p", text: "Il caldo è la vera sfida, quindi lavori con la giornata anziché contro di essa: partenze mattutine, una lunga pausa a mezzogiorno e molta acqua. Una crociera sul Nilo è un'ottima base per famiglie — un hotel galleggiante con piscina che La porta da un sito all'altro — così nessuno passa le ore più calde a camminare avanti e indietro, e c'è sempre dove rinfrescarsi." },
      { kind: "h2", text: "Cibo e stomaci" },
      { kind: "p", text: "Si attenga all'acqua in bottiglia o filtrata, anche per lavarsi i denti, e preferisca i locali affollati e di cucina fresca a qualsiasi cosa sia rimasta a lungo in attesa. Pane, riso, carni alla griglia e frutta fresca tengono contenti la maggior parte dei bambini. Porti dei sali reidratanti per ogni evenienza, e si avvicini gradualmente alla cucina locale anziché lanciarsi la prima sera." },
      { kind: "h2", text: "I viaggi che funzionano" },
      { kind: "p", text: "Il viaggio privato e guidato rende il doppio con una famiglia: una buona guida adatta le storie all'età dei Suoi figli e mantiene la giornata flessibile. Includa le cose che trasformano la storia in avventura: un giro in cammello alle piramidi, una traversata in feluca, le sale delle mummie del museo, una carrozza a Luxor. Azzecchi il ritmo, e l'Egitto diventerà il viaggio di cui i Suoi figli parleranno per anni." },
    ],
  },
};
