/**
 * Russian (ru) alt-overlay (inventory §H, P2). Keyed by image `src` path — NOT
 * slug — because theme slugs are not globally unique and gallery photos have no
 * slug; `src` is the only globally unique key. Values carry ONLY {alt,
 * caption?}; credit / creator / license / page / src stay out. Gallery entries
 * are alt-only (source has no caption); theme-media and city-media carry
 * alt + caption (identical in source, kept identical here). Covers gallery (48)
 * + theme-media (50) + city-media (60) = 158 images. Alt text is
 * descriptive/impersonal (no direct address).
 */
export const altOverlayRu: Record<string, { alt: string; caption?: string }> = {
  // Gallery — real-traveler photos (src/content/gallery.ts); alt only.
  "/assets/gallery/guests-01.webp": { alt: "Четверо путешественников делят напитки и трапезу в бедуинском лагере в пустыне" },
  "/assets/gallery/temples-01.webp": { alt: "Резные колонны большого гипостильного зала Карнакского храма, Луксор" },
  "/assets/gallery/nile-nubia-01.webp": { alt: "Ярко раскрашенные дома нубийской деревни близ Асуана" },
  "/assets/gallery/sinai-desert-01.webp": { alt: "Узкие песчаниковые стены Цветного каньона на Синае" },
  "/assets/gallery/guests-02.webp": { alt: "Египетский гид объясняет путешественнику древние настенные рельефы в храме Луксора" },
  "/assets/gallery/temples-02.webp": { alt: "Фасад музея Шарм-эль-Шейха со статуями фараонов и египетским флагом" },
  "/assets/gallery/nile-nubia-02.webp": { alt: "Терраса нубийского кафе с видом на Нил и лодки близ Асуана" },
  "/assets/gallery/sinai-desert-02.webp": { alt: "Бедуинский лагерь в пустыне с освещённым шатром и подушками вокруг ковра в сумерках" },
  "/assets/gallery/guests-03.webp": { alt: "Туристическая группа делает селфи перед храмом Хатшепсут, Луксор" },
  "/assets/gallery/temples-03.webp": { alt: "Расписной древнеегипетский потолочный рельеф с быком и символами звёзд" },
  "/assets/gallery/nile-nubia-03.webp": { alt: "Красочные дома нубийской деревни на склоне холма на закате близ Асуана" },
  "/assets/gallery/sinai-desert-03.webp": { alt: "Туристы собрались у костра в бедуинском лагере в пустыне в сумерках" },
  "/assets/gallery/guests-04.webp": { alt: "Путешественник позирует у колоссальной статуи Рамсеса II в Большом Египетском музее" },
  "/assets/gallery/temples-04.webp": { alt: "Красочные расписные рельефы на стенах и потолке древнеегипетского храма" },
  "/assets/gallery/nile-nubia-04.webp": { alt: "Фелюга с бирюзовым парусом на Ниле" },
  "/assets/gallery/guests-05.webp": { alt: "Семья позирует со своим египетским гидом перед Луксорским храмом" },
  "/assets/gallery/temples-05.webp": { alt: "Расписной синий рельеф с солнечной ладьёй и божествами в древнем храме" },
  "/assets/gallery/nile-nubia-05.webp": { alt: "Выкрашенный в синий дом в нубийском стиле с украшенными ступенями в сумерках" },
  "/assets/gallery/guests-06.webp": { alt: "Путешественник у экспозиции солнечной ладьи царя Хеопса, Большой Египетский музей" },
  "/assets/gallery/temples-06.webp": { alt: "Расписной синий рельеф с крылатым существом и двумя божествами в древнем храме" },
  "/assets/gallery/nile-nubia-06.webp": { alt: "Украшенный вход в гостевой дом в нубийском стиле в обрамлении раскидистого дерева" },
  "/assets/gallery/guests-07.webp": { alt: "Большая туристическая группа перед храмом Хатшепсут, Луксор" },
  "/assets/gallery/temples-07.webp": { alt: "Посетители рассматривают резные рельефы на стене храма в Мединет-Абу, Луксор" },
  "/assets/gallery/guests-08.webp": { alt: "Двое путешественников позируют с гидом у резных храмовых рельефов в Луксоре" },
  "/assets/gallery/temples-08.webp": { alt: "Расписной синий рельеф со сфинксом, соколом и змеёй в древнем храме" },
  "/assets/gallery/guests-09.webp": { alt: "Улыбающиеся путешественники делают селфи с гидом среди колонн Карнака" },
  "/assets/gallery/temples-09.webp": { alt: "Богато расписанный потолок и хаторические колонны храма Хатхор в Дендере" },
  "/assets/gallery/guests-10.webp": { alt: "Путешественники отдыхают на нильской фелюге на закате" },
  "/assets/gallery/temples-10.webp": { alt: "Высокие колонны с головами Хатхор внутри храма Хатхор в Дендере" },
  "/assets/gallery/guests-11.webp": { alt: "Путешественник и гид позируют у резных батальных рельефов в Мединет-Абу, Луксор" },
  "/assets/gallery/temples-11.webp": { alt: "Расписной синий рельеф с божествами вокруг солнечной ладьи, потолок храма в Дендере" },
  "/assets/gallery/guests-12.webp": { alt: "Четверо путешественников улыбаются для солнечного селфи в храме Луксора" },
  "/assets/gallery/temples-12.webp": { alt: "Пара позирует между Колоссами Мемнона под ясным синим небом, Луксор" },
  "/assets/gallery/guests-13.webp": { alt: "Путешественники позируют со своим египетским гидом у входа в музей" },
  "/assets/gallery/temples-13.webp": { alt: "Расписной рельеф с фигурами с головами соколов на синей стене храма, Дендера" },
  "/assets/gallery/guests-14.webp": { alt: "Семья делает селфи перед храмом Хатшепсут, Луксор" },
  "/assets/gallery/temples-14.webp": { alt: "Ярко расписанные колонны и потолок гипостильного зала храма в Дендере" },
  "/assets/gallery/guests-15.webp": { alt: "Двое путешественников и местный гид улыбаются для селфи в храме на закате" },
  "/assets/gallery/temples-15.webp": { alt: "Расписной рельеф с богиней, поднимающей усыпанное звёздами небо, храм в Дендере" },
  "/assets/gallery/guests-16.webp": { alt: "Двое путешественников сидят на носу традиционной лодки на Ниле" },
  "/assets/gallery/temples-16.webp": { alt: "Расписной астрономический рельеф с богиней-бегемотом и животными, храм в Дендере" },
  "/assets/gallery/guests-17.webp": { alt: "Туристы любуются гигантскими колоннами большого гипостильного зала в Карнаке, Луксор" },
  "/assets/gallery/temples-17.webp": { alt: "Расписной рельеф с богиней неба, поднимающей крылатого скарабея и звёзды, Дендера" },
  "/assets/gallery/guests-18.webp": { alt: "Туристы проходят мимо колоссальной статуи фараона в Карнакском храме, Луксор" },
  "/assets/gallery/temples-18.webp": { alt: "Ряды расписных фигур и иероглифов на синем потолке храма, Дендера" },
  "/assets/gallery/temples-19.webp": { alt: "Аллея сфинксов с головами баранов, ведущая к первому пилону Карнакского храма, Луксор" },
  "/assets/gallery/temples-20.webp": { alt: "Террасный храм Хатшепсут у подножия пустынных скал в Дейр-эль-Бахри, Луксор" },
  "/assets/gallery/temples-21.webp": { alt: "Туристы на аллее сфинксов с головами баранов, ведущей к первому пилону Карнакского храма, Луксор" },
  // Theme media — heritage (src/content/theme-media.ts); alt + caption identical.
  "/assets/themes/heritage/01-giza-pyramids.webp": { alt: "Пирамиды Гизы", caption: "Пирамиды Гизы" },
  "/assets/themes/heritage/02-saqqara-step-pyramid.webp": { alt: "Саккара / Ступенчатая пирамида Джосера", caption: "Саккара / Ступенчатая пирамида Джосера" },
  "/assets/themes/heritage/03-karnak-temple.webp": { alt: "Карнакский храм", caption: "Карнакский храм" },
  "/assets/themes/heritage/04-luxor-temple.webp": { alt: "Луксорский храм", caption: "Луксорский храм" },
  "/assets/themes/heritage/05-abu-simbel.webp": { alt: "Абу-Симбел", caption: "Абу-Симбел" },
  "/assets/themes/heritage/06-philae-temple.webp": { alt: "Храм Филе", caption: "Храм Филе" },
  "/assets/themes/heritage/07-kom-ombo.webp": { alt: "Храм Ком-Омбо", caption: "Храм Ком-Омбо" },
  "/assets/themes/heritage/08-coptic-cairo.webp": { alt: "Коптский Каир", caption: "Коптский Каир" },
  "/assets/themes/heritage/09-islamic-cairo.webp": { alt: "Исламский Каир", caption: "Исламский Каир" },
  "/assets/themes/heritage/10-nile-aswan.webp": { alt: "Долина Нила / Асуан", caption: "Долина Нила / Асуан" },
  // Theme media — the-nile.
  "/assets/themes/the-nile/01-nile-riverbank-kom-ombo-edfu.webp": { alt: "Берег Нила между Ком-Омбо и Эдфу", caption: "Берег Нила между Ком-Омбо и Эдфу" },
  "/assets/themes/the-nile/02-luxor-boats-on-nile.webp": { alt: "Лодки и речная жизнь в Луксоре", caption: "Лодки и речная жизнь в Луксоре" },
  "/assets/themes/the-nile/03-aswan-feluccas.webp": { alt: "Фелюги на Ниле в Асуане", caption: "Фелюги на Ниле в Асуане" },
  "/assets/themes/the-nile/04-aswan-boat-egrets.webp": { alt: "Дикая природа и традиционная лодка на Ниле", caption: "Дикая природа и традиционная лодка на Ниле" },
  "/assets/themes/the-nile/05-elephantine-island.webp": { alt: "Остров Элефантина, Асуан", caption: "Остров Элефантина, Асуан" },
  "/assets/themes/the-nile/06-aswan-wide-nile.webp": { alt: "Широкая панорама Нила в Асуане", caption: "Широкая панорама Нила в Асуане" },
  "/assets/themes/the-nile/07-cairo-nile-skyline-sunset.webp": { alt: "Каир и Нил на закате", caption: "Каир и Нил на закате" },
  "/assets/themes/the-nile/08-cairo-nile-night.webp": { alt: "Нил в Каире ночью", caption: "Нил в Каире ночью" },
  "/assets/themes/the-nile/09-river-nile-near-aswan.webp": { alt: "Пейзаж Нила близ Асуана", caption: "Пейзаж Нила близ Асуана" },
  "/assets/themes/the-nile/10-nile-felucca-aswan.webp": { alt: "Одинокая фелюга на Ниле", caption: "Одинокая фелюга на Ниле" },
  // Theme media — deserts.
  "/assets/themes/deserts/01-white-desert-alien-landscape.webp": { alt: "Белая пустыня / сюрреалистичные скальные образования", caption: "Белая пустыня / сюрреалистичные скальные образования" },
  "/assets/themes/deserts/02-black-desert-panorama.webp": { alt: "Панорама Чёрной пустыни", caption: "Панорама Чёрной пустыни" },
  "/assets/themes/deserts/03-bahariya-oasis.webp": { alt: "Оазис Бахария", caption: "Оазис Бахария" },
  "/assets/themes/deserts/04-siwa-oracle-temple.webp": { alt: "Оазис Сива / Оракул Амона", caption: "Оазис Сива / Оракул Амона" },
  "/assets/themes/deserts/05-fayoum-desert.webp": { alt: "Пустынный пейзаж Фаюма", caption: "Пустынный пейзаж Фаюма" },
  "/assets/themes/deserts/06-sinai-canyon.webp": { alt: "Каньон и горный пейзаж Синая", caption: "Каньон и горный пейзаж Синая" },
  "/assets/themes/deserts/07-nuweiba-desert-road.webp": { alt: "Пустынная дорога Синая / Нувейба", caption: "Пустынная дорога Синая / Нувейба" },
  "/assets/themes/deserts/08-wadi-el-hitan-fennec.webp": { alt: "Вади-эль-Хитан / дикая природа пустыни", caption: "Вади-эль-Хитан / дикая природа пустыни" },
  "/assets/themes/deserts/09-red-sea-mountains.webp": { alt: "Горы Красного моря", caption: "Горы Красного моря" },
  "/assets/themes/deserts/10-saint-catherine-monastery.webp": { alt: "Монастырь Святой Екатерины и горы Синая", caption: "Монастырь Святой Екатерины и горы Синая" },
  // Theme media — red-sea.
  "/assets/themes/red-sea/01-coral-reef-public-domain.webp": { alt: "Коралловый риф Красного моря", caption: "Коралловый риф Красного моря" },
  "/assets/themes/red-sea/02-sharm-coral.webp": { alt: "Коралловый риф Шарм-эль-Шейха", caption: "Коралловый риф Шарм-эль-Шейха" },
  "/assets/themes/red-sea/03-hurghada-coast.webp": { alt: "Побережье Хургады", caption: "Побережье Хургады" },
  "/assets/themes/red-sea/04-marsa-alam.webp": { alt: "Побережье Марса-Алама", caption: "Побережье Марса-Алама" },
  "/assets/themes/red-sea/05-dahab-panorama.webp": { alt: "Панорама побережья Дахаба", caption: "Панорама побережья Дахаба" },
  "/assets/themes/red-sea/06-shadwan-island.webp": { alt: "Пейзаж острова в Красном море", caption: "Пейзаж острова в Красном море" },
  "/assets/themes/red-sea/07-nuweiba-red-sea-mountains.webp": { alt: "Горы и море в Нувейбе", caption: "Горы и море в Нувейбе" },
  "/assets/themes/red-sea/08-red-sea-mountains.webp": { alt: "Горное побережье Красного моря", caption: "Горное побережье Красного моря" },
  "/assets/themes/red-sea/09-dahab-paradise.webp": { alt: "Панорама побережья Дахаба", caption: "Панорама побережья Дахаба" },
  "/assets/themes/red-sea/10-coral-bay-sharm.webp": { alt: "Прибрежная бухта Шарм-эль-Шейха", caption: "Прибрежная бухта Шарм-эль-Шейха" },
  // Theme media — when-to-visit.
  "/assets/themes/when-to-visit/01-nile-at-sunset.webp": { alt: "Река Нил на закате", caption: "Река Нил на закате" },
  "/assets/themes/when-to-visit/02-siwa-cleopatras-bath.webp": { alt: "Оазис Сива / Купальня Клеопатры", caption: "Оазис Сива / Купальня Клеопатры" },
  "/assets/themes/when-to-visit/03-white-desert-rock.webp": { alt: "Скальные образования Белой пустыни", caption: "Скальные образования Белой пустыни" },
  "/assets/themes/when-to-visit/04-red-sea-soma-bay.webp": { alt: "Побережье Красного моря / Сома-Бей", caption: "Побережье Красного моря / Сома-Бей" },
  "/assets/themes/when-to-visit/05-alexandria-beach.webp": { alt: "Средиземноморское побережье / Александрия", caption: "Средиземноморское побережье / Александрия" },
  "/assets/themes/when-to-visit/06-sinai-sunrise.webp": { alt: "Горы Синая на рассвете", caption: "Горы Синая на рассвете" },
  "/assets/themes/when-to-visit/07-dakhla-sand-dunes.webp": { alt: "Оазис Дахла / дюны Сахары", caption: "Оазис Дахла / дюны Сахары" },
  "/assets/themes/when-to-visit/08-aswan-nile.webp": { alt: "Асуан / Долина Нила", caption: "Асуан / Долина Нила" },
  "/assets/themes/when-to-visit/09-nuweiba-mountains.webp": { alt: "Нувейба / горы Синая и Красное море", caption: "Нувейба / горы Синая и Красное море" },
  "/assets/themes/when-to-visit/10-luxor-nile-sunset.webp": { alt: "Луксор / закат на Ниле", caption: "Луксор / закат на Ниле" },
  // City media — alexandria (src/content/city-media.ts); alt + caption identical.
  "/assets/cities/alexandria/01_Alexandria_Egypt_235108463.webp": { alt: "Александрия на средиземноморском побережье", caption: "Александрия на средиземноморском побережье" },
  "/assets/cities/alexandria/02_Citadel_of_Qaitbay_Alexandria_Egypt.webp": { alt: "Крепость Кайт-бей, Александрия, Египет", caption: "Крепость Кайт-бей, Александрия, Египет" },
  "/assets/cities/alexandria/03_Citadel_of_Qaitbay_014.webp": { alt: "Крепость Кайт-бей", caption: "Крепость Кайт-бей" },
  "/assets/cities/alexandria/04_Qaitbay_citadel_in_Alexandria_01.webp": { alt: "Крепость Кайт-бей в Александрии", caption: "Крепость Кайт-бей в Александрии" },
  "/assets/cities/alexandria/05_Qaitbay_citadel_in_Alexandria_02.webp": { alt: "Крепость Кайт-бей в Александрии", caption: "Крепость Кайт-бей в Александрии" },
  "/assets/cities/alexandria/06_Qaitbay_citadel_in_Alexandria_03.webp": { alt: "Крепость Кайт-бей в Александрии", caption: "Крепость Кайт-бей в Александрии" },
  "/assets/cities/alexandria/07_Qaitbay_citadel_in_Alexandria_04.webp": { alt: "Крепость Кайт-бей в Александрии", caption: "Крепость Кайт-бей в Александрии" },
  "/assets/cities/alexandria/08_Qaitbay_citadel_in_Alexandria_05.webp": { alt: "Крепость Кайт-бей в Александрии", caption: "Крепость Кайт-бей в Александрии" },
  "/assets/cities/alexandria/09_Qaitbay_citadel_in_Alexandria_06.webp": { alt: "Крепость Кайт-бей в Александрии", caption: "Крепость Кайт-бей в Александрии" },
  "/assets/cities/alexandria/10_Qaitbay_citadel_in_Alexandria_07.webp": { alt: "Крепость Кайт-бей в Александрии", caption: "Крепость Кайт-бей в Александрии" },
  // City media — aswan.
  "/assets/cities/aswan/01-aswan-nile-r01.webp": { alt: "Панорама Нила в Асуане", caption: "Панорама Нила в Асуане" },
  "/assets/cities/aswan/02-aswan-nile-r03.webp": { alt: "Нил и его берег в Асуане", caption: "Нил и его берег в Асуане" },
  "/assets/cities/aswan/03-philae-temple.webp": { alt: "Храм Филе / остров Агилкия", caption: "Храм Филе / остров Агилкия" },
  "/assets/cities/aswan/04-philae-complex-cc0.webp": { alt: "Храмовый комплекс Филе", caption: "Храмовый комплекс Филе" },
  "/assets/cities/aswan/05-elephantine-island-cc0.webp": { alt: "Остров Элефантина", caption: "Остров Элефантина" },
  "/assets/cities/aswan/06-elephantine-island.webp": { alt: "Речной пейзаж острова Элефантина", caption: "Речной пейзаж острова Элефантина" },
  "/assets/cities/aswan/07-nubian-village.webp": { alt: "Культура нубийской деревни", caption: "Культура нубийской деревни" },
  "/assets/cities/aswan/08-felucca-aswan.webp": { alt: "Фелюга под парусом на Ниле", caption: "Фелюга под парусом на Ниле" },
  "/assets/cities/aswan/09-aswan-high-dam.webp": { alt: "Асуанская высотная плотина", caption: "Асуанская высотная плотина" },
  "/assets/cities/aswan/10-felucca-r04.webp": { alt: "Традиционная фелюга на Ниле", caption: "Традиционная фелюга на Ниле" },
  // City media — cairo.
  "/assets/cities/cairo/01-cairo-cityscape-panorama.webp": { alt: "Панорама города Каира", caption: "Панорама города Каира" },
  "/assets/cities/cairo/02-cairo-citadel-public-domain.webp": { alt: "Цитадель и мечеть Мухаммеда Али", caption: "Цитадель и мечеть Мухаммеда Али" },
  "/assets/cities/cairo/03-khan-el-khalili-cc0.webp": { alt: "Рынок Хан-эль-Халили", caption: "Рынок Хан-эль-Халили" },
  "/assets/cities/cairo/04-muizz-market-street.webp": { alt: "Улица Муизз / Исламский Каир", caption: "Улица Муизз / Исламский Каир" },
  "/assets/cities/cairo/05-al-azhar-courtyard.webp": { alt: "Мечеть аль-Азхар", caption: "Мечеть аль-Азхар" },
  "/assets/cities/cairo/06-cairo-citadel-scenes.webp": { alt: "Фрагмент Каирской цитадели", caption: "Фрагмент Каирской цитадели" },
  "/assets/cities/cairo/07-cairo-museum-public-domain.webp": { alt: "Фасад Египетского музея", caption: "Фасад Египетского музея" },
  "/assets/cities/cairo/08-mosque-of-ibn-tulun.webp": { alt: "Мечеть Ибн Тулуна", caption: "Мечеть Ибн Тулуна" },
  "/assets/cities/cairo/09-cairo-nile-night.webp": { alt: "Нил в Каире ночью", caption: "Нил в Каире ночью" },
  "/assets/cities/cairo/10-city-of-a-thousand-minarets.webp": { alt: "Силуэт и мечети Исламского Каира", caption: "Силуэт и мечети Исламского Каира" },
  // City media — hurghada.
  "/assets/cities/hurghada/01_Egypt-Hurghada-from-plane01.webp": { alt: "Хургада и побережье Красного моря с высоты", caption: "Хургада и побережье Красного моря с высоты" },
  "/assets/cities/hurghada/02_Giftun_Eden_Island.webp": { alt: "Остров Гифтун близ Хургады", caption: "Остров Гифтун близ Хургады" },
  "/assets/cities/hurghada/03_Giftun_Island_Egypte_-_panoramio.webp": { alt: "Остров Гифтун у берегов Хургады", caption: "Остров Гифтун у берегов Хургады" },
  "/assets/cities/hurghada/04_Giftun_Island_Egypte_-_panoramio_1.webp": { alt: "Остров Гифтун у берегов Хургады", caption: "Остров Гифтун у берегов Хургады" },
  "/assets/cities/hurghada/05_Giftun_Island_Egypte_-_panoramio_2.webp": { alt: "Остров Гифтун у берегов Хургады", caption: "Остров Гифтун у берегов Хургады" },
  "/assets/cities/hurghada/06_Giftun_Island_Egypte_-_panoramio_3.webp": { alt: "Остров Гифтун у берегов Хургады", caption: "Остров Гифтун у берегов Хургады" },
  "/assets/cities/hurghada/07_Giftun_Island_Egypte_-_panoramio_4.webp": { alt: "Остров Гифтун у берегов Хургады", caption: "Остров Гифтун у берегов Хургады" },
  "/assets/cities/hurghada/08_Giftun_Island_Egypte_-_panoramio_5.webp": { alt: "Остров Гифтун у берегов Хургады", caption: "Остров Гифтун у берегов Хургады" },
  "/assets/cities/hurghada/09_Giftun_Island_Egypte_-_panoramio_6.webp": { alt: "Остров Гифтун у берегов Хургады", caption: "Остров Гифтун у берегов Хургады" },
  "/assets/cities/hurghada/10_Giftun_Soraya01.webp": { alt: "Пляж острова Гифтун близ Хургады", caption: "Пляж острова Гифтун близ Хургады" },
  // City media — luxor.
  "/assets/cities/luxor/01-karnak-temple.webp": { alt: "Карнакский храм", caption: "Карнакский храм" },
  "/assets/cities/luxor/02-luxor-temple.webp": { alt: "Луксорский храм", caption: "Луксорский храм" },
  "/assets/cities/luxor/03-valley-of-kings.webp": { alt: "Пейзаж Долины царей", caption: "Пейзаж Долины царей" },
  "/assets/cities/luxor/04-valley-kings-tomb.webp": { alt: "Интерьер гробницы в Долине царей", caption: "Интерьер гробницы в Долине царей" },
  "/assets/cities/luxor/05-hatshepsut-temple.webp": { alt: "Храм Хатшепсут", caption: "Храм Хатшепсут" },
  "/assets/cities/luxor/06-medinet-habu.webp": { alt: "Храм Мединет-Абу", caption: "Храм Мединет-Абу" },
  "/assets/cities/luxor/07-colossi-memnon.webp": { alt: "Колоссы Мемнона", caption: "Колоссы Мемнона" },
  "/assets/cities/luxor/08-luxor-nile-sunset.webp": { alt: "Закат на Ниле в Луксоре", caption: "Закат на Ниле в Луксоре" },
  "/assets/cities/luxor/09-luxor-felucca.webp": { alt: "Фелюга на Ниле в Луксоре", caption: "Фелюга на Ниле в Луксоре" },
  "/assets/cities/luxor/10-medinet-habu-entrance.webp": { alt: "Вход в Мединет-Абу", caption: "Вход в Мединет-Абу" },
  // City media — sharm-el-sheikh.
  "/assets/cities/sharm-el-sheikh/01_Divemaster-ready-to-go.webp": { alt: "Дайвинг в Шарм-эль-Шейхе", caption: "Дайвинг в Шарм-эль-Шейхе" },
  "/assets/cities/sharm-el-sheikh/02_Magic_of_FullMoon_between_Palms.webp": { alt: "Полная луна над пальмами Шарм-эль-Шейха", caption: "Полная луна над пальмами Шарм-эль-Шейха" },
  "/assets/cities/sharm-el-sheikh/03_Ras_Mohamed_National_Park_-_panoramio.webp": { alt: "Национальный парк Рас-Мохаммед", caption: "Национальный парк Рас-Мохаммед" },
  "/assets/cities/sharm-el-sheikh/04_Ras_Mohamed_National_Park_2006_-_panoramio.webp": { alt: "Национальный парк Рас-Мохаммед", caption: "Национальный парк Рас-Мохаммед" },
  "/assets/cities/sharm-el-sheikh/05_Ras_Mohammed_-_panoramio.webp": { alt: "Рас-Мохаммед", caption: "Рас-Мохаммед" },
  "/assets/cities/sharm-el-sheikh/06_Tiran_Island_-_Sharm_El_Sheikh_-_South_Sinai_-_Egypt.webp": { alt: "Остров Тиран — Шарм-эль-Шейх — Южный Синай — Египет", caption: "Остров Тиран — Шарм-эль-Шейх — Южный Синай — Египет" },
  "/assets/cities/sharm-el-sheikh/07_Arrecife_de_coral_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_170.webp": { alt: "Коралловый риф в национальном парке Рас-Мохаммед", caption: "Коралловый риф в национальном парке Рас-Мохаммед" },
  "/assets/cities/sharm-el-sheikh/08_Arrecife_de_coral_Acropora_hemprichii_Xenia_umbellata_Siderastrea_savignyana_par.webp": { alt: "Коралловый риф в национальном парке Рас-Мохаммед", caption: "Коралловый риф в национальном парке Рас-Мохаммед" },
  "/assets/cities/sharm-el-sheikh/09_Arrecife_de_coral_Pocillopora_verrucosa_Xenia_umbellata_parque_nacional_Ras_Muha.webp": { alt: "Коралловый риф в национальном парке Рас-Мохаммед", caption: "Коралловый риф в национальном парке Рас-Мохаммед" },
  "/assets/cities/sharm-el-sheikh/10_Coral_Acropora_hemprichii_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_70.webp": { alt: "Коралловый риф в национальном парке Рас-Мохаммед", caption: "Коралловый риф в национальном парке Рас-Мохаммед" },
};
