/**
 * French (fr) alt-overlay (inventory §H, P2). Keyed by image `src` path — NOT
 * slug — because theme slugs are not globally unique and gallery photos have no
 * slug; `src` is the only globally unique key. Values carry ONLY {alt,
 * caption?}; credit / creator / license / page / src stay out. Gallery entries
 * are alt-only (source has no caption); theme-media and city-media carry
 * alt + caption (identical in source, kept identical here). Covers gallery (48)
 * + theme-media (50) + city-media (60) = 158 images. Alt text is
 * descriptive/impersonal (no direct address).
 */
export const altOverlayFr: Record<string, { alt: string; caption?: string }> = {
  // Gallery — real-traveler photos (src/content/gallery.ts); alt only.
  "/assets/gallery/guests-01.webp": { alt: "Quatre voyageurs partageant des boissons et un repas dans un campement bédouin du désert" },
  "/assets/gallery/temples-01.webp": { alt: "Colonnes sculptées de la grande salle hypostyle du temple de Karnak, Louxor" },
  "/assets/gallery/nile-nubia-01.webp": { alt: "Maisons nubiennes aux couleurs vives près d'Assouan" },
  "/assets/gallery/sinai-desert-01.webp": { alt: "Les parois de grès étroites du Canyon coloré dans le Sinaï" },
  "/assets/gallery/guests-02.webp": { alt: "Un guide égyptien expliquant d'anciens reliefs muraux à un voyageur dans un temple de Louxor" },
  "/assets/gallery/temples-02.webp": { alt: "L'extérieur du musée de Charm el-Cheikh avec des statues pharaoniques et un drapeau égyptien" },
  "/assets/gallery/nile-nubia-02.webp": { alt: "La terrasse d'un café nubien dominant le Nil avec des barques près d'Assouan" },
  "/assets/gallery/sinai-desert-02.webp": { alt: "Un campement bédouin dans le désert avec une tente éclairée et des coussins au sol autour d'un tapis au crépuscule" },
  "/assets/gallery/guests-03.webp": { alt: "Un groupe de touristes prenant un selfie devant le temple d'Hatchepsout, Louxor" },
  "/assets/gallery/temples-03.webp": { alt: "Un relief de plafond de l'Égypte ancienne peint, avec un taureau et des symboles d'étoiles" },
  "/assets/gallery/nile-nubia-03.webp": { alt: "Maisons nubiennes colorées sur une colline au coucher du soleil près d'Assouan" },
  "/assets/gallery/sinai-desert-03.webp": { alt: "Des touristes rassemblés autour d'un feu de camp dans un campement bédouin au crépuscule" },
  "/assets/gallery/guests-04.webp": { alt: "Un voyageur posant devant la statue colossale de Ramsès II au Grand Musée égyptien" },
  "/assets/gallery/temples-04.webp": { alt: "Reliefs peints colorés sur les murs et le plafond d'un ancien temple égyptien" },
  "/assets/gallery/nile-nubia-04.webp": { alt: "Une felouque à la voile turquoise sur le Nil" },
  "/assets/gallery/guests-05.webp": { alt: "Une famille posant avec son guide égyptien devant le temple de Louxor" },
  "/assets/gallery/temples-05.webp": { alt: "Un relief bleu peint représentant une barque solaire et des divinités dans un temple antique" },
  "/assets/gallery/nile-nubia-05.webp": { alt: "Une maison de village de style nubien peinte en bleu, aux marches décorées, au crépuscule" },
  "/assets/gallery/guests-06.webp": { alt: "Un voyageur devant l'exposition de la barque solaire du roi Khéops, Grand Musée égyptien" },
  "/assets/gallery/temples-06.webp": { alt: "Un relief bleu peint représentant une créature ailée et deux divinités dans un temple antique" },
  "/assets/gallery/nile-nubia-06.webp": { alt: "L'entrée décorée d'une maison d'hôtes de style nubien encadrée par un arbre feuillu" },
  "/assets/gallery/guests-07.webp": { alt: "Un grand groupe de touristes devant le temple d'Hatchepsout, Louxor" },
  "/assets/gallery/temples-07.webp": { alt: "Des visiteurs observant des reliefs sculptés sur le mur d'un temple à Médinet Habou, Louxor" },
  "/assets/gallery/guests-08.webp": { alt: "Deux voyageurs posant avec leur guide à côté de reliefs sculptés d'un temple à Louxor" },
  "/assets/gallery/temples-08.webp": { alt: "Un relief bleu peint avec un sphinx, un faucon et un serpent dans un temple antique" },
  "/assets/gallery/guests-09.webp": { alt: "Des voyageurs souriants prenant un selfie avec leur guide parmi les colonnes de Karnak" },
  "/assets/gallery/temples-09.webp": { alt: "Le plafond peint richement orné et les colonnes hathoriques du temple d'Hathor à Dendérah" },
  "/assets/gallery/guests-10.webp": { alt: "Des voyageurs se détendant sur une felouque du Nil au coucher du soleil" },
  "/assets/gallery/temples-10.webp": { alt: "Imposantes colonnes à chapiteaux hathoriques à l'intérieur du temple d'Hathor à Dendérah" },
  "/assets/gallery/guests-11.webp": { alt: "Un voyageur et un guide posant près de reliefs de bataille sculptés à Médinet Habou, Louxor" },
  "/assets/gallery/temples-11.webp": { alt: "Un relief bleu peint de divinités autour d'une barque solaire, plafond du temple de Dendérah" },
  "/assets/gallery/guests-12.webp": { alt: "Quatre voyageurs souriant pour un selfie ensoleillé dans un temple de Louxor" },
  "/assets/gallery/temples-12.webp": { alt: "Un couple posant entre les colosses de Memnon sous un ciel bleu dégagé, Louxor" },
  "/assets/gallery/guests-13.webp": { alt: "Des voyageurs posant avec leur guide égyptien devant l'entrée d'un musée" },
  "/assets/gallery/temples-13.webp": { alt: "Un relief peint de figures à tête de faucon sur un mur de temple bleu, Dendérah" },
  "/assets/gallery/guests-14.webp": { alt: "Une famille prenant un selfie devant le temple d'Hatchepsout, Louxor" },
  "/assets/gallery/temples-14.webp": { alt: "Colonnes et plafond aux couleurs vives de la salle hypostyle du temple de Dendérah" },
  "/assets/gallery/guests-15.webp": { alt: "Deux voyageurs et un guide local souriant pour un selfie dans un temple au coucher du soleil" },
  "/assets/gallery/temples-15.webp": { alt: "Un relief peint d'une déesse soulevant le ciel étoilé, temple de Dendérah" },
  "/assets/gallery/guests-16.webp": { alt: "Deux voyageurs assis à la proue d'une embarcation traditionnelle sur le Nil" },
  "/assets/gallery/temples-16.webp": { alt: "Un relief astronomique peint avec une déesse hippopotame et des animaux, temple de Dendérah" },
  "/assets/gallery/guests-17.webp": { alt: "Des touristes admirant les colonnes géantes de la grande salle hypostyle de Karnak, Louxor" },
  "/assets/gallery/temples-17.webp": { alt: "Un relief peint de la déesse du ciel soulevant un scarabée ailé et des étoiles, Dendérah" },
  "/assets/gallery/guests-18.webp": { alt: "Des touristes passant devant une statue colossale de pharaon au temple de Karnak, Louxor" },
  "/assets/gallery/temples-18.webp": { alt: "Des rangées de figures peintes et de hiéroglyphes sur un plafond de temple bleu, Dendérah" },
  "/assets/gallery/temples-19.webp": { alt: "L'allée des sphinx à tête de bélier menant au premier pylône du temple de Karnak, Louxor" },
  "/assets/gallery/temples-20.webp": { alt: "Le temple à terrasses d'Hatchepsout au pied des falaises désertiques de Deir el-Bahari, Louxor" },
  "/assets/gallery/temples-21.webp": { alt: "Des touristes sur l'allée des sphinx à tête de bélier menant au premier pylône du temple de Karnak, Louxor" },
  // Theme media — heritage (src/content/theme-media.ts); alt + caption identical.
  "/assets/themes/heritage/01-giza-pyramids.webp": { alt: "Pyramides de Gizeh", caption: "Pyramides de Gizeh" },
  "/assets/themes/heritage/02-saqqara-step-pyramid.webp": { alt: "Saqqarah / Pyramide à degrés de Djéser", caption: "Saqqarah / Pyramide à degrés de Djéser" },
  "/assets/themes/heritage/03-karnak-temple.webp": { alt: "Temple de Karnak", caption: "Temple de Karnak" },
  "/assets/themes/heritage/04-luxor-temple.webp": { alt: "Temple de Louxor", caption: "Temple de Louxor" },
  "/assets/themes/heritage/05-abu-simbel.webp": { alt: "Abou Simbel", caption: "Abou Simbel" },
  "/assets/themes/heritage/06-philae-temple.webp": { alt: "Temple de Philæ", caption: "Temple de Philæ" },
  "/assets/themes/heritage/07-kom-ombo.webp": { alt: "Temple de Kôm Ombo", caption: "Temple de Kôm Ombo" },
  "/assets/themes/heritage/08-coptic-cairo.webp": { alt: "Le Caire copte", caption: "Le Caire copte" },
  "/assets/themes/heritage/09-islamic-cairo.webp": { alt: "Le Caire islamique", caption: "Le Caire islamique" },
  "/assets/themes/heritage/10-nile-aswan.webp": { alt: "Vallée du Nil / Assouan", caption: "Vallée du Nil / Assouan" },
  // Theme media — the-nile.
  "/assets/themes/the-nile/01-nile-riverbank-kom-ombo-edfu.webp": { alt: "Berge du Nil entre Kôm Ombo et Edfou", caption: "Berge du Nil entre Kôm Ombo et Edfou" },
  "/assets/themes/the-nile/02-luxor-boats-on-nile.webp": { alt: "Bateaux et vie fluviale à Louxor", caption: "Bateaux et vie fluviale à Louxor" },
  "/assets/themes/the-nile/03-aswan-feluccas.webp": { alt: "Felouques sur le Nil à Assouan", caption: "Felouques sur le Nil à Assouan" },
  "/assets/themes/the-nile/04-aswan-boat-egrets.webp": { alt: "Faune et embarcation traditionnelle sur le Nil", caption: "Faune et embarcation traditionnelle sur le Nil" },
  "/assets/themes/the-nile/05-elephantine-island.webp": { alt: "Île Éléphantine, Assouan", caption: "Île Éléphantine, Assouan" },
  "/assets/themes/the-nile/06-aswan-wide-nile.webp": { alt: "Vaste vue du Nil à Assouan", caption: "Vaste vue du Nil à Assouan" },
  "/assets/themes/the-nile/07-cairo-nile-skyline-sunset.webp": { alt: "Le Caire et le Nil au coucher du soleil", caption: "Le Caire et le Nil au coucher du soleil" },
  "/assets/themes/the-nile/08-cairo-nile-night.webp": { alt: "Le Nil du Caire la nuit", caption: "Le Nil du Caire la nuit" },
  "/assets/themes/the-nile/09-river-nile-near-aswan.webp": { alt: "Paysage du Nil près d'Assouan", caption: "Paysage du Nil près d'Assouan" },
  "/assets/themes/the-nile/10-nile-felucca-aswan.webp": { alt: "Une felouque solitaire sur le Nil", caption: "Une felouque solitaire sur le Nil" },
  // Theme media — deserts.
  "/assets/themes/deserts/01-white-desert-alien-landscape.webp": { alt: "Désert blanc / formations rocheuses surréalistes", caption: "Désert blanc / formations rocheuses surréalistes" },
  "/assets/themes/deserts/02-black-desert-panorama.webp": { alt: "Panorama du désert noir", caption: "Panorama du désert noir" },
  "/assets/themes/deserts/03-bahariya-oasis.webp": { alt: "Oasis de Bahariya", caption: "Oasis de Bahariya" },
  "/assets/themes/deserts/04-siwa-oracle-temple.webp": { alt: "Oasis de Siwa / Oracle d'Amon", caption: "Oasis de Siwa / Oracle d'Amon" },
  "/assets/themes/deserts/05-fayoum-desert.webp": { alt: "Paysage désertique du Fayoum", caption: "Paysage désertique du Fayoum" },
  "/assets/themes/deserts/06-sinai-canyon.webp": { alt: "Canyon et paysage montagneux du Sinaï", caption: "Canyon et paysage montagneux du Sinaï" },
  "/assets/themes/deserts/07-nuweiba-desert-road.webp": { alt: "Route du désert du Sinaï / Nuweiba", caption: "Route du désert du Sinaï / Nuweiba" },
  "/assets/themes/deserts/08-wadi-el-hitan-fennec.webp": { alt: "Ouadi El-Hitan / faune du désert", caption: "Ouadi El-Hitan / faune du désert" },
  "/assets/themes/deserts/09-red-sea-mountains.webp": { alt: "Montagnes de la mer Rouge", caption: "Montagnes de la mer Rouge" },
  "/assets/themes/deserts/10-saint-catherine-monastery.webp": { alt: "Monastère Sainte-Catherine et montagnes du Sinaï", caption: "Monastère Sainte-Catherine et montagnes du Sinaï" },
  // Theme media — red-sea.
  "/assets/themes/red-sea/01-coral-reef-public-domain.webp": { alt: "Récif corallien de la mer Rouge", caption: "Récif corallien de la mer Rouge" },
  "/assets/themes/red-sea/02-sharm-coral.webp": { alt: "Récif corallien de Charm el-Cheikh", caption: "Récif corallien de Charm el-Cheikh" },
  "/assets/themes/red-sea/03-hurghada-coast.webp": { alt: "Côte d'Hourghada", caption: "Côte d'Hourghada" },
  "/assets/themes/red-sea/04-marsa-alam.webp": { alt: "Côte de Marsa Alam", caption: "Côte de Marsa Alam" },
  "/assets/themes/red-sea/05-dahab-panorama.webp": { alt: "Panorama du littoral de Dahab", caption: "Panorama du littoral de Dahab" },
  "/assets/themes/red-sea/06-shadwan-island.webp": { alt: "Paysage d'une île de la mer Rouge", caption: "Paysage d'une île de la mer Rouge" },
  "/assets/themes/red-sea/07-nuweiba-red-sea-mountains.webp": { alt: "Montagnes et mer à Nuweiba", caption: "Montagnes et mer à Nuweiba" },
  "/assets/themes/red-sea/08-red-sea-mountains.webp": { alt: "Côte montagneuse de la mer Rouge", caption: "Côte montagneuse de la mer Rouge" },
  "/assets/themes/red-sea/09-dahab-paradise.webp": { alt: "Panorama du littoral de Dahab", caption: "Panorama du littoral de Dahab" },
  "/assets/themes/red-sea/10-coral-bay-sharm.webp": { alt: "Baie côtière de Charm el-Cheikh", caption: "Baie côtière de Charm el-Cheikh" },
  // Theme media — when-to-visit.
  "/assets/themes/when-to-visit/01-nile-at-sunset.webp": { alt: "Le Nil au coucher du soleil", caption: "Le Nil au coucher du soleil" },
  "/assets/themes/when-to-visit/02-siwa-cleopatras-bath.webp": { alt: "Oasis de Siwa / Bain de Cléopâtre", caption: "Oasis de Siwa / Bain de Cléopâtre" },
  "/assets/themes/when-to-visit/03-white-desert-rock.webp": { alt: "Formations rocheuses du désert blanc", caption: "Formations rocheuses du désert blanc" },
  "/assets/themes/when-to-visit/04-red-sea-soma-bay.webp": { alt: "Côte de la mer Rouge / Soma Bay", caption: "Côte de la mer Rouge / Soma Bay" },
  "/assets/themes/when-to-visit/05-alexandria-beach.webp": { alt: "Côte méditerranéenne / Alexandrie", caption: "Côte méditerranéenne / Alexandrie" },
  "/assets/themes/when-to-visit/06-sinai-sunrise.webp": { alt: "Montagnes du Sinaï au lever du soleil", caption: "Montagnes du Sinaï au lever du soleil" },
  "/assets/themes/when-to-visit/07-dakhla-sand-dunes.webp": { alt: "Oasis de Dakhla / dunes du Sahara", caption: "Oasis de Dakhla / dunes du Sahara" },
  "/assets/themes/when-to-visit/08-aswan-nile.webp": { alt: "Assouan / Vallée du Nil", caption: "Assouan / Vallée du Nil" },
  "/assets/themes/when-to-visit/09-nuweiba-mountains.webp": { alt: "Nuweiba / montagnes du Sinaï et mer Rouge", caption: "Nuweiba / montagnes du Sinaï et mer Rouge" },
  "/assets/themes/when-to-visit/10-luxor-nile-sunset.webp": { alt: "Louxor / coucher de soleil sur le Nil", caption: "Louxor / coucher de soleil sur le Nil" },
  // City media — alexandria (src/content/city-media.ts); alt + caption identical.
  "/assets/cities/alexandria/01_Alexandria_Egypt_235108463.webp": { alt: "Alexandrie sur la côte méditerranéenne", caption: "Alexandrie sur la côte méditerranéenne" },
  "/assets/cities/alexandria/02_Citadel_of_Qaitbay_Alexandria_Egypt.webp": { alt: "Citadelle de Qaitbay, Alexandrie, Égypte", caption: "Citadelle de Qaitbay, Alexandrie, Égypte" },
  "/assets/cities/alexandria/03_Citadel_of_Qaitbay_014.webp": { alt: "Citadelle de Qaitbay", caption: "Citadelle de Qaitbay" },
  "/assets/cities/alexandria/04_Qaitbay_citadel_in_Alexandria_01.webp": { alt: "Citadelle de Qaitbay à Alexandrie", caption: "Citadelle de Qaitbay à Alexandrie" },
  "/assets/cities/alexandria/05_Qaitbay_citadel_in_Alexandria_02.webp": { alt: "Citadelle de Qaitbay à Alexandrie", caption: "Citadelle de Qaitbay à Alexandrie" },
  "/assets/cities/alexandria/06_Qaitbay_citadel_in_Alexandria_03.webp": { alt: "Citadelle de Qaitbay à Alexandrie", caption: "Citadelle de Qaitbay à Alexandrie" },
  "/assets/cities/alexandria/07_Qaitbay_citadel_in_Alexandria_04.webp": { alt: "Citadelle de Qaitbay à Alexandrie", caption: "Citadelle de Qaitbay à Alexandrie" },
  "/assets/cities/alexandria/08_Qaitbay_citadel_in_Alexandria_05.webp": { alt: "Citadelle de Qaitbay à Alexandrie", caption: "Citadelle de Qaitbay à Alexandrie" },
  "/assets/cities/alexandria/09_Qaitbay_citadel_in_Alexandria_06.webp": { alt: "Citadelle de Qaitbay à Alexandrie", caption: "Citadelle de Qaitbay à Alexandrie" },
  "/assets/cities/alexandria/10_Qaitbay_citadel_in_Alexandria_07.webp": { alt: "Citadelle de Qaitbay à Alexandrie", caption: "Citadelle de Qaitbay à Alexandrie" },
  // City media — aswan.
  "/assets/cities/aswan/01-aswan-nile-r01.webp": { alt: "Panorama du Nil à Assouan", caption: "Panorama du Nil à Assouan" },
  "/assets/cities/aswan/02-aswan-nile-r03.webp": { alt: "Le Nil et sa berge à Assouan", caption: "Le Nil et sa berge à Assouan" },
  "/assets/cities/aswan/03-philae-temple.webp": { alt: "Temple de Philæ / île d'Aguilkia", caption: "Temple de Philæ / île d'Aguilkia" },
  "/assets/cities/aswan/04-philae-complex-cc0.webp": { alt: "Complexe du temple de Philæ", caption: "Complexe du temple de Philæ" },
  "/assets/cities/aswan/05-elephantine-island-cc0.webp": { alt: "Île Éléphantine", caption: "Île Éléphantine" },
  "/assets/cities/aswan/06-elephantine-island.webp": { alt: "Scène fluviale à l'île Éléphantine", caption: "Scène fluviale à l'île Éléphantine" },
  "/assets/cities/aswan/07-nubian-village.webp": { alt: "Culture d'un village nubien", caption: "Culture d'un village nubien" },
  "/assets/cities/aswan/08-felucca-aswan.webp": { alt: "Felouque naviguant sur le Nil", caption: "Felouque naviguant sur le Nil" },
  "/assets/cities/aswan/09-aswan-high-dam.webp": { alt: "Haut barrage d'Assouan", caption: "Haut barrage d'Assouan" },
  "/assets/cities/aswan/10-felucca-r04.webp": { alt: "Felouque traditionnelle sur le Nil", caption: "Felouque traditionnelle sur le Nil" },
  // City media — cairo.
  "/assets/cities/cairo/01-cairo-cityscape-panorama.webp": { alt: "Panorama de la silhouette du Caire", caption: "Panorama de la silhouette du Caire" },
  "/assets/cities/cairo/02-cairo-citadel-public-domain.webp": { alt: "Citadelle et mosquée de Méhémet Ali", caption: "Citadelle et mosquée de Méhémet Ali" },
  "/assets/cities/cairo/03-khan-el-khalili-cc0.webp": { alt: "Marché de Khan el-Khalili", caption: "Marché de Khan el-Khalili" },
  "/assets/cities/cairo/04-muizz-market-street.webp": { alt: "Rue Muizz / Le Caire islamique", caption: "Rue Muizz / Le Caire islamique" },
  "/assets/cities/cairo/05-al-azhar-courtyard.webp": { alt: "Mosquée al-Azhar", caption: "Mosquée al-Azhar" },
  "/assets/cities/cairo/06-cairo-citadel-scenes.webp": { alt: "Détail de la citadelle du Caire", caption: "Détail de la citadelle du Caire" },
  "/assets/cities/cairo/07-cairo-museum-public-domain.webp": { alt: "Extérieur du Musée égyptien", caption: "Extérieur du Musée égyptien" },
  "/assets/cities/cairo/08-mosque-of-ibn-tulun.webp": { alt: "Mosquée d'Ibn Touloun", caption: "Mosquée d'Ibn Touloun" },
  "/assets/cities/cairo/09-cairo-nile-night.webp": { alt: "Le Nil du Caire la nuit", caption: "Le Nil du Caire la nuit" },
  "/assets/cities/cairo/10-city-of-a-thousand-minarets.webp": { alt: "Silhouette et mosquées du Caire islamique", caption: "Silhouette et mosquées du Caire islamique" },
  // City media — hurghada.
  "/assets/cities/hurghada/01_Egypt-Hurghada-from-plane01.webp": { alt: "Hourghada et la côte de la mer Rouge vues du ciel", caption: "Hourghada et la côte de la mer Rouge vues du ciel" },
  "/assets/cities/hurghada/02_Giftun_Eden_Island.webp": { alt: "Île de Giftoun, près d'Hourghada", caption: "Île de Giftoun, près d'Hourghada" },
  "/assets/cities/hurghada/03_Giftun_Island_Egypte_-_panoramio.webp": { alt: "Île de Giftoun au large d'Hourghada", caption: "Île de Giftoun au large d'Hourghada" },
  "/assets/cities/hurghada/04_Giftun_Island_Egypte_-_panoramio_1.webp": { alt: "Île de Giftoun au large d'Hourghada", caption: "Île de Giftoun au large d'Hourghada" },
  "/assets/cities/hurghada/05_Giftun_Island_Egypte_-_panoramio_2.webp": { alt: "Île de Giftoun au large d'Hourghada", caption: "Île de Giftoun au large d'Hourghada" },
  "/assets/cities/hurghada/06_Giftun_Island_Egypte_-_panoramio_3.webp": { alt: "Île de Giftoun au large d'Hourghada", caption: "Île de Giftoun au large d'Hourghada" },
  "/assets/cities/hurghada/07_Giftun_Island_Egypte_-_panoramio_4.webp": { alt: "Île de Giftoun au large d'Hourghada", caption: "Île de Giftoun au large d'Hourghada" },
  "/assets/cities/hurghada/08_Giftun_Island_Egypte_-_panoramio_5.webp": { alt: "Île de Giftoun au large d'Hourghada", caption: "Île de Giftoun au large d'Hourghada" },
  "/assets/cities/hurghada/09_Giftun_Island_Egypte_-_panoramio_6.webp": { alt: "Île de Giftoun au large d'Hourghada", caption: "Île de Giftoun au large d'Hourghada" },
  "/assets/cities/hurghada/10_Giftun_Soraya01.webp": { alt: "Plage de l'île de Giftoun près d'Hourghada", caption: "Plage de l'île de Giftoun près d'Hourghada" },
  // City media — luxor.
  "/assets/cities/luxor/01-karnak-temple.webp": { alt: "Temple de Karnak", caption: "Temple de Karnak" },
  "/assets/cities/luxor/02-luxor-temple.webp": { alt: "Temple de Louxor", caption: "Temple de Louxor" },
  "/assets/cities/luxor/03-valley-of-kings.webp": { alt: "Paysage de la Vallée des Rois", caption: "Paysage de la Vallée des Rois" },
  "/assets/cities/luxor/04-valley-kings-tomb.webp": { alt: "Intérieur d'une tombe de la Vallée des Rois", caption: "Intérieur d'une tombe de la Vallée des Rois" },
  "/assets/cities/luxor/05-hatshepsut-temple.webp": { alt: "Temple d'Hatchepsout", caption: "Temple d'Hatchepsout" },
  "/assets/cities/luxor/06-medinet-habu.webp": { alt: "Temple de Médinet Habou", caption: "Temple de Médinet Habou" },
  "/assets/cities/luxor/07-colossi-memnon.webp": { alt: "Colosses de Memnon", caption: "Colosses de Memnon" },
  "/assets/cities/luxor/08-luxor-nile-sunset.webp": { alt: "Coucher de soleil sur le Nil à Louxor", caption: "Coucher de soleil sur le Nil à Louxor" },
  "/assets/cities/luxor/09-luxor-felucca.webp": { alt: "Felouque sur le Nil à Louxor", caption: "Felouque sur le Nil à Louxor" },
  "/assets/cities/luxor/10-medinet-habu-entrance.webp": { alt: "Entrée de Médinet Habou", caption: "Entrée de Médinet Habou" },
  // City media — sharm-el-sheikh.
  "/assets/cities/sharm-el-sheikh/01_Divemaster-ready-to-go.webp": { alt: "Plongée à Charm el-Cheikh", caption: "Plongée à Charm el-Cheikh" },
  "/assets/cities/sharm-el-sheikh/02_Magic_of_FullMoon_between_Palms.webp": { alt: "Pleine lune sur les palmiers de Charm el-Cheikh", caption: "Pleine lune sur les palmiers de Charm el-Cheikh" },
  "/assets/cities/sharm-el-sheikh/03_Ras_Mohamed_National_Park_-_panoramio.webp": { alt: "Parc national de Ras Mohammed", caption: "Parc national de Ras Mohammed" },
  "/assets/cities/sharm-el-sheikh/04_Ras_Mohamed_National_Park_2006_-_panoramio.webp": { alt: "Parc national de Ras Mohammed", caption: "Parc national de Ras Mohammed" },
  "/assets/cities/sharm-el-sheikh/05_Ras_Mohammed_-_panoramio.webp": { alt: "Ras Mohammed", caption: "Ras Mohammed" },
  "/assets/cities/sharm-el-sheikh/06_Tiran_Island_-_Sharm_El_Sheikh_-_South_Sinai_-_Egypt.webp": { alt: "Île de Tiran - Charm el-Cheikh - Sinaï du Sud - Égypte", caption: "Île de Tiran - Charm el-Cheikh - Sinaï du Sud - Égypte" },
  "/assets/cities/sharm-el-sheikh/07_Arrecife_de_coral_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_170.webp": { alt: "Récif corallien dans le parc national de Ras Muhammad", caption: "Récif corallien dans le parc national de Ras Muhammad" },
  "/assets/cities/sharm-el-sheikh/08_Arrecife_de_coral_Acropora_hemprichii_Xenia_umbellata_Siderastrea_savignyana_par.webp": { alt: "Récif corallien dans le parc national de Ras Muhammad", caption: "Récif corallien dans le parc national de Ras Muhammad" },
  "/assets/cities/sharm-el-sheikh/09_Arrecife_de_coral_Pocillopora_verrucosa_Xenia_umbellata_parque_nacional_Ras_Muha.webp": { alt: "Récif corallien dans le parc national de Ras Muhammad", caption: "Récif corallien dans le parc national de Ras Muhammad" },
  "/assets/cities/sharm-el-sheikh/10_Coral_Acropora_hemprichii_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_70.webp": { alt: "Récif corallien dans le parc national de Ras Muhammad", caption: "Récif corallien dans le parc national de Ras Muhammad" },
};
