/**
 * Spanish (es) alt-overlay (inventory §H, P2). Keyed by image `src` path — NOT
 * slug — because theme slugs are not globally unique (e.g. "red-sea-mountains"
 * appears in both deserts and red-sea) and gallery photos have no slug; `src`
 * is the only globally unique key. Values carry ONLY {alt, caption?}; credit /
 * creator / license / page / src stay out. Gallery entries are alt-only (source
 * has no caption); theme-media and city-media carry alt + caption (identical in
 * source, kept identical here). Covers gallery (48) + theme-media (50) +
 * city-media (60) = 158 images. Alt text is descriptive/impersonal (no direct
 * address), so the usted register is not surfaced here.
 */
export const altOverlayEs: Record<string, { alt: string; caption?: string }> = {
  // Gallery — real-traveler photos (src/content/gallery.ts); alt only.
  "/assets/gallery/guests-01.webp": { alt: "Cuatro viajeros comparten bebidas y una comida en un campamento del desierto de estilo beduino" },
  "/assets/gallery/temples-01.webp": { alt: "Columnas talladas de la gran sala hipóstila del templo de Karnak, Luxor" },
  "/assets/gallery/nile-nubia-01.webp": { alt: "Casas de una aldea nubia pintadas de colores vivos cerca de Asuán" },
  "/assets/gallery/sinai-desert-01.webp": { alt: "Las estrechas paredes de arenisca del Cañón de Colores en el Sinaí" },
  "/assets/gallery/guests-02.webp": { alt: "Un guía egipcio explica antiguos relieves murales a un viajero en un templo de Luxor" },
  "/assets/gallery/temples-02.webp": { alt: "El exterior del Museo de Sharm el-Sheikh con estatuas faraónicas y una bandera egipcia" },
  "/assets/gallery/nile-nubia-02.webp": { alt: "La terraza de un café nubio con vistas al Nilo y botes de remos cerca de Asuán" },
  "/assets/gallery/sinai-desert-02.webp": { alt: "Un campamento beduino en el desierto con una tienda iluminada y cojines en el suelo alrededor de una alfombra al atardecer" },
  "/assets/gallery/guests-03.webp": { alt: "Un grupo turístico se hace un selfie frente al templo de Hatshepsut, Luxor" },
  "/assets/gallery/temples-03.webp": { alt: "Un relieve pintado de un techo del antiguo Egipto con un toro y símbolos de estrellas" },
  "/assets/gallery/nile-nubia-03.webp": { alt: "Coloridas casas de una aldea nubia en una ladera al atardecer cerca de Asuán" },
  "/assets/gallery/sinai-desert-03.webp": { alt: "Turistas reunidos alrededor de una fogata en un campamento beduino del desierto al atardecer" },
  "/assets/gallery/guests-04.webp": { alt: "Un viajero posa ante la colosal estatua de Ramsés II en el Gran Museo Egipcio" },
  "/assets/gallery/temples-04.webp": { alt: "Coloridos relieves pintados en las paredes y el techo de un antiguo templo egipcio" },
  "/assets/gallery/nile-nubia-04.webp": { alt: "Una faluca con una vela turquesa en el Nilo" },
  "/assets/gallery/guests-05.webp": { alt: "Una familia posa con su guía egipcio frente al templo de Luxor" },
  "/assets/gallery/temples-05.webp": { alt: "Un relieve azul pintado de una barca solar y deidades en un templo antiguo" },
  "/assets/gallery/nile-nubia-05.webp": { alt: "Una casa de aldea de estilo nubio pintada de azul con escalones decorados al atardecer" },
  "/assets/gallery/guests-06.webp": { alt: "Un viajero en la exposición de la barca solar del rey Keops, Gran Museo Egipcio" },
  "/assets/gallery/temples-06.webp": { alt: "Un relieve azul pintado de una criatura alada y dos deidades en un templo antiguo" },
  "/assets/gallery/nile-nubia-06.webp": { alt: "La entrada decorada de una casa de huéspedes de estilo nubio enmarcada por un árbol frondoso" },
  "/assets/gallery/guests-07.webp": { alt: "Un gran grupo turístico frente al templo de Hatshepsut, Luxor" },
  "/assets/gallery/temples-07.webp": { alt: "Visitantes contemplan relieves tallados en el muro de un templo en Medinet Habu, Luxor" },
  "/assets/gallery/guests-08.webp": { alt: "Dos viajeros posan con su guía junto a relieves tallados de un templo en Luxor" },
  "/assets/gallery/temples-08.webp": { alt: "Un relieve azul pintado con una esfinge, un halcón y una serpiente en un templo antiguo" },
  "/assets/gallery/guests-09.webp": { alt: "Viajeros sonrientes se hacen un selfie con su guía entre las columnas de Karnak" },
  "/assets/gallery/temples-09.webp": { alt: "El ornamentado techo pintado y las columnas hathóricas del templo de Hathor en Dendera" },
  "/assets/gallery/guests-10.webp": { alt: "Viajeros relajándose en una faluca del Nilo al atardecer" },
  "/assets/gallery/temples-10.webp": { alt: "Imponentes columnas con capiteles hathóricos en el interior del templo de Hathor en Dendera" },
  "/assets/gallery/guests-11.webp": { alt: "Un viajero y su guía posan junto a relieves tallados de batallas en Medinet Habu, Luxor" },
  "/assets/gallery/temples-11.webp": { alt: "Un relieve azul pintado de deidades alrededor de una barca solar, techo del templo de Dendera" },
  "/assets/gallery/guests-12.webp": { alt: "Cuatro viajeros sonríen para un selfie soleado en un templo de Luxor" },
  "/assets/gallery/temples-12.webp": { alt: "Una pareja posa entre los Colosos de Memnón bajo un cielo azul despejado, Luxor" },
  "/assets/gallery/guests-13.webp": { alt: "Viajeros posan con su guía egipcio a la entrada de un museo" },
  "/assets/gallery/temples-13.webp": { alt: "Un relieve pintado de figuras con cabeza de halcón en un muro azul de un templo, Dendera" },
  "/assets/gallery/guests-14.webp": { alt: "Una familia se hace un selfie frente al templo de Hatshepsut, Luxor" },
  "/assets/gallery/temples-14.webp": { alt: "Columnas y techo pintados con colores vivos de la sala hipóstila del templo de Dendera" },
  "/assets/gallery/guests-15.webp": { alt: "Dos viajeros y un guía local sonríen para un selfie en un templo al atardecer" },
  "/assets/gallery/temples-15.webp": { alt: "Un relieve pintado de una diosa que alza el cielo cuajado de estrellas, templo de Dendera" },
  "/assets/gallery/guests-16.webp": { alt: "Dos viajeros sentados en la proa de una embarcación tradicional en el Nilo" },
  "/assets/gallery/temples-16.webp": { alt: "Un relieve astronómico pintado con una diosa hipopótamo y animales, templo de Dendera" },
  "/assets/gallery/guests-17.webp": { alt: "Turistas admiran las gigantescas columnas de la gran sala hipóstila de Karnak, Luxor" },
  "/assets/gallery/temples-17.webp": { alt: "Un relieve pintado de la diosa del cielo que eleva un escarabajo alado y estrellas, Dendera" },
  "/assets/gallery/guests-18.webp": { alt: "Turistas pasan junto a una colosal estatua de un faraón en el templo de Karnak, Luxor" },
  "/assets/gallery/temples-18.webp": { alt: "Hileras de figuras pintadas y jeroglíficos en el techo azul de un templo, Dendera" },
  "/assets/gallery/temples-19.webp": { alt: "La avenida de esfinges con cabeza de carnero que conduce al primer pilono del templo de Karnak, Luxor" },
  "/assets/gallery/temples-20.webp": { alt: "El templo escalonado de Hatshepsut bajo los acantilados del desierto en Deir el-Bahari, Luxor" },
  "/assets/gallery/temples-21.webp": { alt: "Turistas en la avenida de esfinges con cabeza de carnero que conduce al primer pilono del templo de Karnak, Luxor" },
  // Theme media (src/content/theme-media.ts); alt + caption (identical in source).
  "/assets/themes/heritage/01-giza-pyramids.webp": { alt: "Pirámides de Guiza", caption: "Pirámides de Guiza" },
  "/assets/themes/heritage/02-saqqara-step-pyramid.webp": { alt: "Saqqara / Pirámide escalonada de Zoser", caption: "Saqqara / Pirámide escalonada de Zoser" },
  "/assets/themes/heritage/03-karnak-temple.webp": { alt: "Templo de Karnak", caption: "Templo de Karnak" },
  "/assets/themes/heritage/04-luxor-temple.webp": { alt: "Templo de Luxor", caption: "Templo de Luxor" },
  "/assets/themes/heritage/05-abu-simbel.webp": { alt: "Abu Simbel", caption: "Abu Simbel" },
  "/assets/themes/heritage/06-philae-temple.webp": { alt: "Templo de File", caption: "Templo de File" },
  "/assets/themes/heritage/07-kom-ombo.webp": { alt: "Templo de Kom Ombo", caption: "Templo de Kom Ombo" },
  "/assets/themes/heritage/08-coptic-cairo.webp": { alt: "El Cairo copto", caption: "El Cairo copto" },
  "/assets/themes/heritage/09-islamic-cairo.webp": { alt: "El Cairo islámico", caption: "El Cairo islámico" },
  "/assets/themes/heritage/10-nile-aswan.webp": { alt: "Valle del Nilo / Asuán", caption: "Valle del Nilo / Asuán" },
  "/assets/themes/the-nile/01-nile-riverbank-kom-ombo-edfu.webp": { alt: "Ribera del Nilo entre Kom Ombo y Edfu", caption: "Ribera del Nilo entre Kom Ombo y Edfu" },
  "/assets/themes/the-nile/02-luxor-boats-on-nile.webp": { alt: "Barcas y vida fluvial en Luxor", caption: "Barcas y vida fluvial en Luxor" },
  "/assets/themes/the-nile/03-aswan-feluccas.webp": { alt: "Falucas en el Nilo en Asuán", caption: "Falucas en el Nilo en Asuán" },
  "/assets/themes/the-nile/04-aswan-boat-egrets.webp": { alt: "Fauna y embarcación tradicional en el Nilo", caption: "Fauna y embarcación tradicional en el Nilo" },
  "/assets/themes/the-nile/05-elephantine-island.webp": { alt: "Isla Elefantina, Asuán", caption: "Isla Elefantina, Asuán" },
  "/assets/themes/the-nile/06-aswan-wide-nile.webp": { alt: "Amplia vista del Nilo en Asuán", caption: "Amplia vista del Nilo en Asuán" },
  "/assets/themes/the-nile/07-cairo-nile-skyline-sunset.webp": { alt: "El Cairo y el Nilo al atardecer", caption: "El Cairo y el Nilo al atardecer" },
  "/assets/themes/the-nile/08-cairo-nile-night.webp": { alt: "El Nilo de El Cairo de noche", caption: "El Nilo de El Cairo de noche" },
  "/assets/themes/the-nile/09-river-nile-near-aswan.webp": { alt: "Paisaje del Nilo cerca de Asuán", caption: "Paisaje del Nilo cerca de Asuán" },
  "/assets/themes/the-nile/10-nile-felucca-aswan.webp": { alt: "Una faluca solitaria en el Nilo", caption: "Una faluca solitaria en el Nilo" },
  "/assets/themes/deserts/01-white-desert-alien-landscape.webp": { alt: "Desierto Blanco / formaciones rocosas surrealistas", caption: "Desierto Blanco / formaciones rocosas surrealistas" },
  "/assets/themes/deserts/02-black-desert-panorama.webp": { alt: "Panorámica del Desierto Negro", caption: "Panorámica del Desierto Negro" },
  "/assets/themes/deserts/03-bahariya-oasis.webp": { alt: "Oasis de Bahariya", caption: "Oasis de Bahariya" },
  "/assets/themes/deserts/04-siwa-oracle-temple.webp": { alt: "Oasis de Siwa / Oráculo de Amón", caption: "Oasis de Siwa / Oráculo de Amón" },
  "/assets/themes/deserts/05-fayoum-desert.webp": { alt: "Paisaje desértico de El Fayún", caption: "Paisaje desértico de El Fayún" },
  "/assets/themes/deserts/06-sinai-canyon.webp": { alt: "Cañón y paisaje montañoso del Sinaí", caption: "Cañón y paisaje montañoso del Sinaí" },
  "/assets/themes/deserts/07-nuweiba-desert-road.webp": { alt: "Carretera del desierto del Sinaí / Nuweiba", caption: "Carretera del desierto del Sinaí / Nuweiba" },
  "/assets/themes/deserts/08-wadi-el-hitan-fennec.webp": { alt: "Wadi El Hitan / fauna del desierto", caption: "Wadi El Hitan / fauna del desierto" },
  "/assets/themes/deserts/09-red-sea-mountains.webp": { alt: "Montañas del mar Rojo", caption: "Montañas del mar Rojo" },
  "/assets/themes/deserts/10-saint-catherine-monastery.webp": { alt: "Monasterio de Santa Catalina y montañas del Sinaí", caption: "Monasterio de Santa Catalina y montañas del Sinaí" },
  "/assets/themes/red-sea/01-coral-reef-public-domain.webp": { alt: "Arrecife de coral del mar Rojo", caption: "Arrecife de coral del mar Rojo" },
  "/assets/themes/red-sea/02-sharm-coral.webp": { alt: "Arrecife de coral de Sharm el-Sheikh", caption: "Arrecife de coral de Sharm el-Sheikh" },
  "/assets/themes/red-sea/03-hurghada-coast.webp": { alt: "Costa de Hurghada", caption: "Costa de Hurghada" },
  "/assets/themes/red-sea/04-marsa-alam.webp": { alt: "Costa de Marsa Alam", caption: "Costa de Marsa Alam" },
  "/assets/themes/red-sea/05-dahab-panorama.webp": { alt: "Panorámica del litoral de Dahab", caption: "Panorámica del litoral de Dahab" },
  "/assets/themes/red-sea/06-shadwan-island.webp": { alt: "Paisaje de una isla del mar Rojo", caption: "Paisaje de una isla del mar Rojo" },
  "/assets/themes/red-sea/07-nuweiba-red-sea-mountains.webp": { alt: "Montañas y mar en Nuweiba", caption: "Montañas y mar en Nuweiba" },
  "/assets/themes/red-sea/08-red-sea-mountains.webp": { alt: "Costa montañosa del mar Rojo", caption: "Costa montañosa del mar Rojo" },
  "/assets/themes/red-sea/09-dahab-paradise.webp": { alt: "Panorámica del litoral de Dahab", caption: "Panorámica del litoral de Dahab" },
  "/assets/themes/red-sea/10-coral-bay-sharm.webp": { alt: "Bahía costera de Sharm el-Sheikh", caption: "Bahía costera de Sharm el-Sheikh" },
  "/assets/themes/when-to-visit/01-nile-at-sunset.webp": { alt: "El río Nilo al atardecer", caption: "El río Nilo al atardecer" },
  "/assets/themes/when-to-visit/02-siwa-cleopatras-bath.webp": { alt: "Oasis de Siwa / Baño de Cleopatra", caption: "Oasis de Siwa / Baño de Cleopatra" },
  "/assets/themes/when-to-visit/03-white-desert-rock.webp": { alt: "Formaciones rocosas del Desierto Blanco", caption: "Formaciones rocosas del Desierto Blanco" },
  "/assets/themes/when-to-visit/04-red-sea-soma-bay.webp": { alt: "Costa del mar Rojo / Soma Bay", caption: "Costa del mar Rojo / Soma Bay" },
  "/assets/themes/when-to-visit/05-alexandria-beach.webp": { alt: "Costa mediterránea / Alejandría", caption: "Costa mediterránea / Alejandría" },
  "/assets/themes/when-to-visit/06-sinai-sunrise.webp": { alt: "Montañas del Sinaí al amanecer", caption: "Montañas del Sinaí al amanecer" },
  "/assets/themes/when-to-visit/07-dakhla-sand-dunes.webp": { alt: "Oasis de Dajla / dunas del Sáhara", caption: "Oasis de Dajla / dunas del Sáhara" },
  "/assets/themes/when-to-visit/08-aswan-nile.webp": { alt: "Asuán / Valle del Nilo", caption: "Asuán / Valle del Nilo" },
  "/assets/themes/when-to-visit/09-nuweiba-mountains.webp": { alt: "Nuweiba / montañas del Sinaí y mar Rojo", caption: "Nuweiba / montañas del Sinaí y mar Rojo" },
  "/assets/themes/when-to-visit/10-luxor-nile-sunset.webp": { alt: "Luxor / atardecer en el Nilo", caption: "Luxor / atardecer en el Nilo" },
  // City media (src/content/city-media.ts); alt + caption (identical in source).
  "/assets/cities/alexandria/01_Alexandria_Egypt_235108463.webp": { alt: "Alejandría en la costa mediterránea", caption: "Alejandría en la costa mediterránea" },
  "/assets/cities/alexandria/02_Citadel_of_Qaitbay_Alexandria_Egypt.webp": { alt: "Ciudadela de Qaitbay, Alejandría, Egipto", caption: "Ciudadela de Qaitbay, Alejandría, Egipto" },
  "/assets/cities/alexandria/03_Citadel_of_Qaitbay_014.webp": { alt: "Ciudadela de Qaitbay", caption: "Ciudadela de Qaitbay" },
  "/assets/cities/alexandria/04_Qaitbay_citadel_in_Alexandria_01.webp": { alt: "Ciudadela de Qaitbay en Alejandría", caption: "Ciudadela de Qaitbay en Alejandría" },
  "/assets/cities/alexandria/05_Qaitbay_citadel_in_Alexandria_02.webp": { alt: "Ciudadela de Qaitbay en Alejandría", caption: "Ciudadela de Qaitbay en Alejandría" },
  "/assets/cities/alexandria/06_Qaitbay_citadel_in_Alexandria_03.webp": { alt: "Ciudadela de Qaitbay en Alejandría", caption: "Ciudadela de Qaitbay en Alejandría" },
  "/assets/cities/alexandria/07_Qaitbay_citadel_in_Alexandria_04.webp": { alt: "Ciudadela de Qaitbay en Alejandría", caption: "Ciudadela de Qaitbay en Alejandría" },
  "/assets/cities/alexandria/08_Qaitbay_citadel_in_Alexandria_05.webp": { alt: "Ciudadela de Qaitbay en Alejandría", caption: "Ciudadela de Qaitbay en Alejandría" },
  "/assets/cities/alexandria/09_Qaitbay_citadel_in_Alexandria_06.webp": { alt: "Ciudadela de Qaitbay en Alejandría", caption: "Ciudadela de Qaitbay en Alejandría" },
  "/assets/cities/alexandria/10_Qaitbay_citadel_in_Alexandria_07.webp": { alt: "Ciudadela de Qaitbay en Alejandría", caption: "Ciudadela de Qaitbay en Alejandría" },
  "/assets/cities/aswan/01-aswan-nile-r01.webp": { alt: "Panorámica del Nilo en Asuán", caption: "Panorámica del Nilo en Asuán" },
  "/assets/cities/aswan/02-aswan-nile-r03.webp": { alt: "El Nilo y su ribera en Asuán", caption: "El Nilo y su ribera en Asuán" },
  "/assets/cities/aswan/03-philae-temple.webp": { alt: "Templo de File / isla de Agilkia", caption: "Templo de File / isla de Agilkia" },
  "/assets/cities/aswan/04-philae-complex-cc0.webp": { alt: "Complejo del templo de File", caption: "Complejo del templo de File" },
  "/assets/cities/aswan/05-elephantine-island-cc0.webp": { alt: "Isla Elefantina", caption: "Isla Elefantina" },
  "/assets/cities/aswan/06-elephantine-island.webp": { alt: "Escena fluvial en la isla Elefantina", caption: "Escena fluvial en la isla Elefantina" },
  "/assets/cities/aswan/07-nubian-village.webp": { alt: "Cultura de una aldea nubia", caption: "Cultura de una aldea nubia" },
  "/assets/cities/aswan/08-felucca-aswan.webp": { alt: "Una faluca navegando por el Nilo", caption: "Una faluca navegando por el Nilo" },
  "/assets/cities/aswan/09-aswan-high-dam.webp": { alt: "Presa Alta de Asuán", caption: "Presa Alta de Asuán" },
  "/assets/cities/aswan/10-felucca-r04.webp": { alt: "Faluca tradicional en el Nilo", caption: "Faluca tradicional en el Nilo" },
  "/assets/cities/cairo/01-cairo-cityscape-panorama.webp": { alt: "Panorámica del horizonte de El Cairo", caption: "Panorámica del horizonte de El Cairo" },
  "/assets/cities/cairo/02-cairo-citadel-public-domain.webp": { alt: "Ciudadela y mezquita de Muhammad Ali", caption: "Ciudadela y mezquita de Muhammad Ali" },
  "/assets/cities/cairo/03-khan-el-khalili-cc0.webp": { alt: "Mercado de Khan el-Khalili", caption: "Mercado de Khan el-Khalili" },
  "/assets/cities/cairo/04-muizz-market-street.webp": { alt: "Calle Muizz / El Cairo islámico", caption: "Calle Muizz / El Cairo islámico" },
  "/assets/cities/cairo/05-al-azhar-courtyard.webp": { alt: "Mezquita de Al-Azhar", caption: "Mezquita de Al-Azhar" },
  "/assets/cities/cairo/06-cairo-citadel-scenes.webp": { alt: "Detalle de la Ciudadela de El Cairo", caption: "Detalle de la Ciudadela de El Cairo" },
  "/assets/cities/cairo/07-cairo-museum-public-domain.webp": { alt: "Exterior del Museo Egipcio", caption: "Exterior del Museo Egipcio" },
  "/assets/cities/cairo/08-mosque-of-ibn-tulun.webp": { alt: "Mezquita de Ibn Tulún", caption: "Mezquita de Ibn Tulún" },
  "/assets/cities/cairo/09-cairo-nile-night.webp": { alt: "El Nilo de El Cairo de noche", caption: "El Nilo de El Cairo de noche" },
  "/assets/cities/cairo/10-city-of-a-thousand-minarets.webp": { alt: "Horizonte y mezquitas de El Cairo islámico", caption: "Horizonte y mezquitas de El Cairo islámico" },
  "/assets/cities/hurghada/01_Egypt-Hurghada-from-plane01.webp": { alt: "Hurghada y la costa del mar Rojo desde el aire", caption: "Hurghada y la costa del mar Rojo desde el aire" },
  "/assets/cities/hurghada/02_Giftun_Eden_Island.webp": { alt: "Isla de Giftun, cerca de Hurghada", caption: "Isla de Giftun, cerca de Hurghada" },
  "/assets/cities/hurghada/03_Giftun_Island_Egypte_-_panoramio.webp": { alt: "Isla de Giftun frente a Hurghada", caption: "Isla de Giftun frente a Hurghada" },
  "/assets/cities/hurghada/04_Giftun_Island_Egypte_-_panoramio_1.webp": { alt: "Isla de Giftun frente a Hurghada", caption: "Isla de Giftun frente a Hurghada" },
  "/assets/cities/hurghada/05_Giftun_Island_Egypte_-_panoramio_2.webp": { alt: "Isla de Giftun frente a Hurghada", caption: "Isla de Giftun frente a Hurghada" },
  "/assets/cities/hurghada/06_Giftun_Island_Egypte_-_panoramio_3.webp": { alt: "Isla de Giftun frente a Hurghada", caption: "Isla de Giftun frente a Hurghada" },
  "/assets/cities/hurghada/07_Giftun_Island_Egypte_-_panoramio_4.webp": { alt: "Isla de Giftun frente a Hurghada", caption: "Isla de Giftun frente a Hurghada" },
  "/assets/cities/hurghada/08_Giftun_Island_Egypte_-_panoramio_5.webp": { alt: "Isla de Giftun frente a Hurghada", caption: "Isla de Giftun frente a Hurghada" },
  "/assets/cities/hurghada/09_Giftun_Island_Egypte_-_panoramio_6.webp": { alt: "Isla de Giftun frente a Hurghada", caption: "Isla de Giftun frente a Hurghada" },
  "/assets/cities/hurghada/10_Giftun_Soraya01.webp": { alt: "Playa de la isla de Giftun cerca de Hurghada", caption: "Playa de la isla de Giftun cerca de Hurghada" },
  "/assets/cities/luxor/01-karnak-temple.webp": { alt: "Templo de Karnak", caption: "Templo de Karnak" },
  "/assets/cities/luxor/02-luxor-temple.webp": { alt: "Templo de Luxor", caption: "Templo de Luxor" },
  "/assets/cities/luxor/03-valley-of-kings.webp": { alt: "Paisaje del Valle de los Reyes", caption: "Paisaje del Valle de los Reyes" },
  "/assets/cities/luxor/04-valley-kings-tomb.webp": { alt: "Interior de una tumba del Valle de los Reyes", caption: "Interior de una tumba del Valle de los Reyes" },
  "/assets/cities/luxor/05-hatshepsut-temple.webp": { alt: "Templo de Hatshepsut", caption: "Templo de Hatshepsut" },
  "/assets/cities/luxor/06-medinet-habu.webp": { alt: "Templo de Medinet Habu", caption: "Templo de Medinet Habu" },
  "/assets/cities/luxor/07-colossi-memnon.webp": { alt: "Colosos de Memnón", caption: "Colosos de Memnón" },
  "/assets/cities/luxor/08-luxor-nile-sunset.webp": { alt: "Atardecer en el Nilo en Luxor", caption: "Atardecer en el Nilo en Luxor" },
  "/assets/cities/luxor/09-luxor-felucca.webp": { alt: "Faluca en el Nilo a su paso por Luxor", caption: "Faluca en el Nilo a su paso por Luxor" },
  "/assets/cities/luxor/10-medinet-habu-entrance.webp": { alt: "Entrada de Medinet Habu", caption: "Entrada de Medinet Habu" },
  "/assets/cities/sharm-el-sheikh/01_Divemaster-ready-to-go.webp": { alt: "Buceo en Sharm el-Sheikh", caption: "Buceo en Sharm el-Sheikh" },
  "/assets/cities/sharm-el-sheikh/02_Magic_of_FullMoon_between_Palms.webp": { alt: "Luna llena sobre las palmeras de Sharm el-Sheikh", caption: "Luna llena sobre las palmeras de Sharm el-Sheikh" },
  "/assets/cities/sharm-el-sheikh/03_Ras_Mohamed_National_Park_-_panoramio.webp": { alt: "Parque Nacional de Ras Mohamed", caption: "Parque Nacional de Ras Mohamed" },
  "/assets/cities/sharm-el-sheikh/04_Ras_Mohamed_National_Park_2006_-_panoramio.webp": { alt: "Parque Nacional de Ras Mohamed", caption: "Parque Nacional de Ras Mohamed" },
  "/assets/cities/sharm-el-sheikh/05_Ras_Mohammed_-_panoramio.webp": { alt: "Ras Mohammed", caption: "Ras Mohammed" },
  "/assets/cities/sharm-el-sheikh/06_Tiran_Island_-_Sharm_El_Sheikh_-_South_Sinai_-_Egypt.webp": { alt: "Isla de Tirán - Sharm el-Sheikh - Sinaí del Sur - Egipto", caption: "Isla de Tirán - Sharm el-Sheikh - Sinaí del Sur - Egipto" },
  "/assets/cities/sharm-el-sheikh/07_Arrecife_de_coral_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_170.webp": { alt: "Arrecife de coral en el Parque Nacional de Ras Muhammad", caption: "Arrecife de coral en el Parque Nacional de Ras Muhammad" },
  "/assets/cities/sharm-el-sheikh/08_Arrecife_de_coral_Acropora_hemprichii_Xenia_umbellata_Siderastrea_savignyana_par.webp": { alt: "Arrecife de coral en el Parque Nacional de Ras Muhammad", caption: "Arrecife de coral en el Parque Nacional de Ras Muhammad" },
  "/assets/cities/sharm-el-sheikh/09_Arrecife_de_coral_Pocillopora_verrucosa_Xenia_umbellata_parque_nacional_Ras_Muha.webp": { alt: "Arrecife de coral en el Parque Nacional de Ras Muhammad", caption: "Arrecife de coral en el Parque Nacional de Ras Muhammad" },
  "/assets/cities/sharm-el-sheikh/10_Coral_Acropora_hemprichii_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_70.webp": { alt: "Arrecife de coral en el Parque Nacional de Ras Muhammad", caption: "Arrecife de coral en el Parque Nacional de Ras Muhammad" },
};
