/**
 * Curated city photography for the six destination pages (alexandria / aswan /
 * cairo / hurghada / luxor / sharm-el-sheikh) plus their on-page attribution.
 *
 * GENERATED by scripts/gen-city-media.mjs from the Wikimedia Commons image sets
 * (scripts/convert-city-images.mjs emits the WebP + dimensions; each city ships
 * .meta/<slug>/manifest.json OR .meta/<slug>/ATTRIBUTION.json with the required
 * creator/license/source-page metadata). Do not hand-edit — re-run the generator.
 *
 * Every image is CC-licensed or public-domain; on-page credit (creator + license
 * + Commons link) is REQUIRED and rendered by <ImageCredits>. alt/caption are
 * source-grounded (manifest subject / cleaned Commons title), never invented.
 * These English strings are shared across all locales for now (English-first);
 * lift into the i18n dictionaries when the pages are translated.
 *
 * The shape mirrors src/content/theme-media.ts so the shared theme toolkit
 * (FeatureRows / PlaceCards / ThemeGallery / ImageCredits) consumes both.
 */

export type CitySlug =
  | "alexandria"
  | "aswan"
  | "cairo"
  | "hurghada"
  | "luxor"
  | "sharm-el-sheikh";

export interface ImageCredit {
  /** Title of the source work on Wikimedia Commons. */
  title: string;
  /** Attributed author/creator string, verbatim from the metadata. */
  creator: string;
  /** License short name, e.g. "CC BY 4.0", "Public domain", "CC0". */
  license: string;
  /** Canonical Commons file page (attribution target). */
  page: string;
}

export interface CityImage {
  /** Stable id within a city, e.g. "philae-temple". */
  slug: string;
  /** Path under /public — optimized WebP. */
  src: string;
  /** Intrinsic pixel dimensions of the WebP (for next/image + masonry). */
  width: number;
  height: number;
  /** Descriptive English alt text. */
  alt: string;
  /** Short English caption for gallery/credit rows. */
  caption: string;
  credit: ImageCredit;
}

export const cityMedia: Record<CitySlug, CityImage[]> = {
  "alexandria": [
    {
      "slug": "alexandria-egypt-235108463",
      "src": "/assets/cities/alexandria/01_Alexandria_Egypt_235108463.webp",
      "width": 1280,
      "height": 1038,
      "alt": "Alexandria on the Mediterranean coast",
      "caption": "Alexandria on the Mediterranean coast",
      "credit": {
        "title": "Alexandria Egypt (235108463).jpeg",
        "creator": "Ahnaf Saber",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Alexandria_Egypt_(235108463).jpeg"
      }
    },
    {
      "slug": "citadel-of-qaitbay-alexandria-egypt",
      "src": "/assets/cities/alexandria/02_Citadel_of_Qaitbay_Alexandria_Egypt.webp",
      "width": 1280,
      "height": 853,
      "alt": "Citadel of Qaitbay, Alexandria, Egypt",
      "caption": "Citadel of Qaitbay, Alexandria, Egypt",
      "credit": {
        "title": "Citadel of Qaitbay, Alexandria, Egypt.jpg",
        "creator": "Argenberg",
        "license": "CC BY 2.0",
        "page": "https://commons.wikimedia.org/wiki/File:Citadel_of_Qaitbay,_Alexandria,_Egypt.jpg"
      }
    },
    {
      "slug": "citadel-of-qaitbay-014",
      "src": "/assets/cities/alexandria/03_Citadel_of_Qaitbay_014.webp",
      "width": 1280,
      "height": 1120,
      "alt": "Citadel of Qaitbay",
      "caption": "Citadel of Qaitbay",
      "credit": {
        "title": "Citadel of Qaitbay 014.JPG",
        "creator": "لا روسا",
        "license": "CC BY-SA 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Citadel_of_Qaitbay_014.JPG"
      }
    },
    {
      "slug": "qaitbay-citadel-in-alexandria-01",
      "src": "/assets/cities/alexandria/04_Qaitbay_citadel_in_Alexandria_01.webp",
      "width": 1280,
      "height": 575,
      "alt": "Qaitbay citadel in Alexandria",
      "caption": "Qaitbay citadel in Alexandria",
      "credit": {
        "title": "Qaitbay citadel in Alexandria 01.jpg",
        "creator": "Aimty17",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Qaitbay_citadel_in_Alexandria_01.jpg"
      }
    },
    {
      "slug": "qaitbay-citadel-in-alexandria-02",
      "src": "/assets/cities/alexandria/05_Qaitbay_citadel_in_Alexandria_02.webp",
      "width": 1280,
      "height": 575,
      "alt": "Qaitbay citadel in Alexandria",
      "caption": "Qaitbay citadel in Alexandria",
      "credit": {
        "title": "Qaitbay citadel in Alexandria 02.jpg",
        "creator": "Aimty17",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Qaitbay_citadel_in_Alexandria_02.jpg"
      }
    },
    {
      "slug": "qaitbay-citadel-in-alexandria-03",
      "src": "/assets/cities/alexandria/06_Qaitbay_citadel_in_Alexandria_03.webp",
      "width": 1280,
      "height": 575,
      "alt": "Qaitbay citadel in Alexandria",
      "caption": "Qaitbay citadel in Alexandria",
      "credit": {
        "title": "Qaitbay citadel in Alexandria 03.jpg",
        "creator": "Aimty17",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Qaitbay_citadel_in_Alexandria_03.jpg"
      }
    },
    {
      "slug": "qaitbay-citadel-in-alexandria-04",
      "src": "/assets/cities/alexandria/07_Qaitbay_citadel_in_Alexandria_04.webp",
      "width": 1280,
      "height": 575,
      "alt": "Qaitbay citadel in Alexandria",
      "caption": "Qaitbay citadel in Alexandria",
      "credit": {
        "title": "Qaitbay citadel in Alexandria 04.jpg",
        "creator": "Aimty17",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Qaitbay_citadel_in_Alexandria_04.jpg"
      }
    },
    {
      "slug": "qaitbay-citadel-in-alexandria-05",
      "src": "/assets/cities/alexandria/08_Qaitbay_citadel_in_Alexandria_05.webp",
      "width": 1280,
      "height": 575,
      "alt": "Qaitbay citadel in Alexandria",
      "caption": "Qaitbay citadel in Alexandria",
      "credit": {
        "title": "Qaitbay citadel in Alexandria 05.jpg",
        "creator": "Aimty17",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Qaitbay_citadel_in_Alexandria_05.jpg"
      }
    },
    {
      "slug": "qaitbay-citadel-in-alexandria-06",
      "src": "/assets/cities/alexandria/09_Qaitbay_citadel_in_Alexandria_06.webp",
      "width": 1280,
      "height": 575,
      "alt": "Qaitbay citadel in Alexandria",
      "caption": "Qaitbay citadel in Alexandria",
      "credit": {
        "title": "Qaitbay citadel in Alexandria 06.jpg",
        "creator": "Aimty17",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Qaitbay_citadel_in_Alexandria_06.jpg"
      }
    },
    {
      "slug": "qaitbay-citadel-in-alexandria-07",
      "src": "/assets/cities/alexandria/10_Qaitbay_citadel_in_Alexandria_07.webp",
      "width": 1280,
      "height": 575,
      "alt": "Qaitbay citadel in Alexandria",
      "caption": "Qaitbay citadel in Alexandria",
      "credit": {
        "title": "Qaitbay citadel in Alexandria 07.jpg",
        "creator": "Aimty17",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Qaitbay_citadel_in_Alexandria_07.jpg"
      }
    }
  ],
  "aswan": [
    {
      "slug": "aswan-nile-r01",
      "src": "/assets/cities/aswan/01-aswan-nile-r01.webp",
      "width": 2000,
      "height": 1309,
      "alt": "Aswan Nile panorama",
      "caption": "Aswan Nile panorama",
      "credit": {
        "title": "Aswan Nile R01",
        "creator": "Marc Ryckaert (MJJR)",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Aswan_Nile_R01.jpg"
      }
    },
    {
      "slug": "aswan-nile-r03",
      "src": "/assets/cities/aswan/02-aswan-nile-r03.webp",
      "width": 2000,
      "height": 1210,
      "alt": "Nile and riverbank at Aswan",
      "caption": "Nile and riverbank at Aswan",
      "credit": {
        "title": "Aswan Nile R03",
        "creator": "Marc Ryckaert (MJJR)",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Aswan_Nile_R03.jpg"
      }
    },
    {
      "slug": "philae-temple",
      "src": "/assets/cities/aswan/03-philae-temple.webp",
      "width": 2000,
      "height": 1428,
      "alt": "Philae Temple / Agilkia Island",
      "caption": "Philae Temple / Agilkia Island",
      "credit": {
        "title": "PHILAE TEMPLE",
        "creator": "Hesham Farouk Ragab",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:PHILAE_TEMPLE.jpg"
      }
    },
    {
      "slug": "philae-complex-cc0",
      "src": "/assets/cities/aswan/04-philae-complex-cc0.webp",
      "width": 2000,
      "height": 1501,
      "alt": "Philae Temple complex",
      "caption": "Philae Temple complex",
      "credit": {
        "title": "Philae Temple Complex, Agilkia Island, Aswan",
        "creator": "Warren LeMay",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Philae_Temple_Complex,_Agilkia_Island,_Aswan,_AG,_EGY_(48027052466).jpg"
      }
    },
    {
      "slug": "elephantine-island-cc0",
      "src": "/assets/cities/aswan/05-elephantine-island-cc0.webp",
      "width": 2000,
      "height": 1500,
      "alt": "Elephantine Island",
      "caption": "Elephantine Island",
      "credit": {
        "title": "Elephantine Island, Aswan",
        "creator": "Warren LeMay",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Elephantine_Island,_Aswan,_AG,_EGY_(48025587842).jpg"
      }
    },
    {
      "slug": "elephantine-island",
      "src": "/assets/cities/aswan/06-elephantine-island.webp",
      "width": 2000,
      "height": 1328,
      "alt": "Elephantine Island river scene",
      "caption": "Elephantine Island river scene",
      "credit": {
        "title": "Aswan Elephantine Island R02",
        "creator": "Marc Ryckaert",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Aswan_Elephantine_Island_R02.jpg"
      }
    },
    {
      "slug": "nubian-village",
      "src": "/assets/cities/aswan/07-nubian-village.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Nubian village culture",
      "caption": "Nubian village culture",
      "credit": {
        "title": "Nubian Village at Aswan",
        "creator": "David Broad",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nubian_Village_at_Aswan_-_panoramio.jpg"
      }
    },
    {
      "slug": "felucca-aswan",
      "src": "/assets/cities/aswan/08-felucca-aswan.webp",
      "width": 1500,
      "height": 2000,
      "alt": "Felucca sailing on the Nile",
      "caption": "Felucca sailing on the Nile",
      "credit": {
        "title": "Felucca in Aswan, March 2023 01",
        "creator": "Votpuske",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Felucca_in_Aswan,_March_2023_01.jpg"
      }
    },
    {
      "slug": "aswan-high-dam",
      "src": "/assets/cities/aswan/09-aswan-high-dam.webp",
      "width": 2000,
      "height": 1125,
      "alt": "Aswan High Dam",
      "caption": "Aswan High Dam",
      "credit": {
        "title": "By ovedc - Aswan High Dam - 05",
        "creator": "Ovedc",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:By_ovedc_-_Aswan_High_Dam_-_05.jpg"
      }
    },
    {
      "slug": "felucca-r04",
      "src": "/assets/cities/aswan/10-felucca-r04.webp",
      "width": 1430,
      "height": 2000,
      "alt": "Traditional felucca on the Nile",
      "caption": "Traditional felucca on the Nile",
      "credit": {
        "title": "Felucca R04",
        "creator": "Marc Ryckaert (MJJR)",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Felucca_R04.jpg"
      }
    }
  ],
  "cairo": [
    {
      "slug": "cairo-cityscape-panorama",
      "src": "/assets/cities/cairo/01-cairo-cityscape-panorama.webp",
      "width": 2000,
      "height": 659,
      "alt": "Cairo skyline panorama",
      "caption": "Cairo skyline panorama",
      "credit": {
        "title": "Cairo cityscape, Egypt, North Africa",
        "creator": "Mstyslav Chernov",
        "license": "CC BY-SA 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Cairo_cityscape._Egypt,_North_Africa.jpg"
      }
    },
    {
      "slug": "cairo-citadel-public-domain",
      "src": "/assets/cities/cairo/02-cairo-citadel-public-domain.webp",
      "width": 2000,
      "height": 1596,
      "alt": "Citadel and Mosque of Muhammad Ali",
      "caption": "Citadel and Mosque of Muhammad Ali",
      "credit": {
        "title": "Cairo. Citadel and Mosque of Mohammed Ali",
        "creator": "Library of Congress / PPOC",
        "license": "Public domain",
        "page": "https://commons.wikimedia.org/wiki/File:Cairo._Citadel_and_Mosque_of_Mohammet_Ali_LCCN92500797.jpg"
      }
    },
    {
      "slug": "khan-el-khalili-cc0",
      "src": "/assets/cities/cairo/03-khan-el-khalili-cc0.webp",
      "width": 1500,
      "height": 2000,
      "alt": "Khan el-Khalili market",
      "caption": "Khan el-Khalili market",
      "credit": {
        "title": "Khan el-Khalili, Old Cairo",
        "creator": "Warren LeMay",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Khan_el-Khalili,_Old_Cairo,_al-Qāhirah,_CG,_EGY_(40944891953).jpg"
      }
    },
    {
      "slug": "muizz-market-street",
      "src": "/assets/cities/cairo/04-muizz-market-street.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Muizz Street / Islamic Cairo",
      "caption": "Muizz Street / Islamic Cairo",
      "credit": {
        "title": "Egypt, Cairo, Muizz Market Street, Islamic Cairo",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Egypt,_Cairo,_Muizz_Market_Street,_Islamic_Cairo.jpg"
      }
    },
    {
      "slug": "al-azhar-courtyard",
      "src": "/assets/cities/cairo/05-al-azhar-courtyard.webp",
      "width": 2000,
      "height": 1500,
      "alt": "Al-Azhar Mosque",
      "caption": "Al-Azhar Mosque",
      "credit": {
        "title": "Courtyard of Al-Azhar Mosque Cairo Egypt 2019",
        "creator": "Radosław Botev",
        "license": "CC BY 3.0 pl",
        "page": "https://commons.wikimedia.org/wiki/File:Courtyard_of_Al-Azhar_Mosque_Cairo_Egypt_2019_(1).jpg"
      }
    },
    {
      "slug": "cairo-citadel-scenes",
      "src": "/assets/cities/cairo/06-cairo-citadel-scenes.webp",
      "width": 2000,
      "height": 1500,
      "alt": "Cairo Citadel detail",
      "caption": "Cairo Citadel detail",
      "credit": {
        "title": "Scenes from Cairo Citadel (25986)",
        "creator": "Amr F.Nagy",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Scenes_from_Cairo_Citadel_(25986).jpg"
      }
    },
    {
      "slug": "cairo-museum-public-domain",
      "src": "/assets/cities/cairo/07-cairo-museum-public-domain.webp",
      "width": 2000,
      "height": 1476,
      "alt": "Egyptian Museum exterior",
      "caption": "Egyptian Museum exterior",
      "credit": {
        "title": "Egyptian views; Cairo, Museum of Cairo, exterior",
        "creator": "Matson Collection",
        "license": "Public domain",
        "page": "https://commons.wikimedia.org/wiki/File:Egyptian_views;_Cairo_(Masr)._Museum_of_Cairo,_exterior_LOC_matpc.01484.jpg"
      }
    },
    {
      "slug": "mosque-of-ibn-tulun",
      "src": "/assets/cities/cairo/08-mosque-of-ibn-tulun.webp",
      "width": 2000,
      "height": 1862,
      "alt": "Mosque of Ibn Tulun",
      "caption": "Mosque of Ibn Tulun",
      "credit": {
        "title": "Egypt, Mosque of Tulun, Exterior, Cairo",
        "creator": "Brooklyn Museum",
        "license": "No restrictions",
        "page": "https://commons.wikimedia.org/wiki/File:Egypt,_Mosque_of_Tulun,_Exterior,_Cairo.jpg"
      }
    },
    {
      "slug": "cairo-nile-night",
      "src": "/assets/cities/cairo/09-cairo-nile-night.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Cairo Nile at night",
      "caption": "Cairo Nile at night",
      "credit": {
        "title": "Egypt, Night Cairo and river Nile, Zamalek city lights",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Egypt,_Night_Cairo_and_river_Nile,_Zamalek_city_lights.jpg"
      }
    },
    {
      "slug": "city-of-a-thousand-minarets",
      "src": "/assets/cities/cairo/10-city-of-a-thousand-minarets.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Islamic Cairo skyline and mosques",
      "caption": "Islamic Cairo skyline and mosques",
      "credit": {
        "title": "Egypt, Cairo, Islamic Cairo, the City of a Thousand Minarets",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Egypt,_Cairo,_Islamic_Cairo,_the_City_of_a_Thousand_Minarets.jpg"
      }
    }
  ],
  "hurghada": [
    {
      "slug": "egypt-hurghada-from-plane01",
      "src": "/assets/cities/hurghada/01_Egypt-Hurghada-from-plane01.webp",
      "width": 1280,
      "height": 960,
      "alt": "Hurghada and the Red Sea coast from the air",
      "caption": "Hurghada and the Red Sea coast from the air",
      "credit": {
        "title": "Egypt-Hurghada-from-plane01.jpg",
        "creator": "No machine-readable author provided. Ebief assumed (based on copyright claims).",
        "license": "CC BY-SA 2.5",
        "page": "https://commons.wikimedia.org/wiki/File:Egypt-Hurghada-from-plane01.jpg"
      }
    },
    {
      "slug": "giftun-eden-island",
      "src": "/assets/cities/hurghada/02_Giftun_Eden_Island.webp",
      "width": 1280,
      "height": 720,
      "alt": "Giftun Island, near Hurghada",
      "caption": "Giftun Island, near Hurghada",
      "credit": {
        "title": "Giftun, Eden Island.jpg",
        "creator": "Vojtasekd",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun,_Eden_Island.jpg"
      }
    },
    {
      "slug": "giftun-island-egypte-panoramio",
      "src": "/assets/cities/hurghada/03_Giftun_Island_Egypte_-_panoramio.webp",
      "width": 1280,
      "height": 721,
      "alt": "Giftun Island off Hurghada",
      "caption": "Giftun Island off Hurghada",
      "credit": {
        "title": "Giftun Island Egypte - panoramio.jpg",
        "creator": "E v Schoonhoven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Island_Egypte_-_panoramio.jpg"
      }
    },
    {
      "slug": "giftun-island-egypte-panoramio-1",
      "src": "/assets/cities/hurghada/04_Giftun_Island_Egypte_-_panoramio_1.webp",
      "width": 1280,
      "height": 721,
      "alt": "Giftun Island off Hurghada",
      "caption": "Giftun Island off Hurghada",
      "credit": {
        "title": "Giftun Island Egypte - panoramio (1).jpg",
        "creator": "E v Schoonhoven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Island_Egypte_-_panoramio_(1).jpg"
      }
    },
    {
      "slug": "giftun-island-egypte-panoramio-2",
      "src": "/assets/cities/hurghada/05_Giftun_Island_Egypte_-_panoramio_2.webp",
      "width": 1280,
      "height": 721,
      "alt": "Giftun Island off Hurghada",
      "caption": "Giftun Island off Hurghada",
      "credit": {
        "title": "Giftun Island Egypte - panoramio (2).jpg",
        "creator": "E v Schoonhoven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Island_Egypte_-_panoramio_(2).jpg"
      }
    },
    {
      "slug": "giftun-island-egypte-panoramio-3",
      "src": "/assets/cities/hurghada/06_Giftun_Island_Egypte_-_panoramio_3.webp",
      "width": 1280,
      "height": 721,
      "alt": "Giftun Island off Hurghada",
      "caption": "Giftun Island off Hurghada",
      "credit": {
        "title": "Giftun Island Egypte - panoramio (3).jpg",
        "creator": "E v Schoonhoven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Island_Egypte_-_panoramio_(3).jpg"
      }
    },
    {
      "slug": "giftun-island-egypte-panoramio-4",
      "src": "/assets/cities/hurghada/07_Giftun_Island_Egypte_-_panoramio_4.webp",
      "width": 1280,
      "height": 721,
      "alt": "Giftun Island off Hurghada",
      "caption": "Giftun Island off Hurghada",
      "credit": {
        "title": "Giftun Island Egypte - panoramio (4).jpg",
        "creator": "E v Schoonhoven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Island_Egypte_-_panoramio_(4).jpg"
      }
    },
    {
      "slug": "giftun-island-egypte-panoramio-5",
      "src": "/assets/cities/hurghada/08_Giftun_Island_Egypte_-_panoramio_5.webp",
      "width": 1280,
      "height": 721,
      "alt": "Giftun Island off Hurghada",
      "caption": "Giftun Island off Hurghada",
      "credit": {
        "title": "Giftun Island Egypte - panoramio (5).jpg",
        "creator": "E v Schoonhoven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Island_Egypte_-_panoramio_(5).jpg"
      }
    },
    {
      "slug": "giftun-island-egypte-panoramio-6",
      "src": "/assets/cities/hurghada/09_Giftun_Island_Egypte_-_panoramio_6.webp",
      "width": 1280,
      "height": 721,
      "alt": "Giftun Island off Hurghada",
      "caption": "Giftun Island off Hurghada",
      "credit": {
        "title": "Giftun Island Egypte - panoramio (6).jpg",
        "creator": "E v Schoonhoven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Island_Egypte_-_panoramio_(6).jpg"
      }
    },
    {
      "slug": "giftun-soraya01",
      "src": "/assets/cities/hurghada/10_Giftun_Soraya01.webp",
      "width": 1280,
      "height": 960,
      "alt": "Giftun Island beach near Hurghada",
      "caption": "Giftun Island beach near Hurghada",
      "credit": {
        "title": "Giftun Soraya01.JPG",
        "creator": "user:vberger",
        "license": "Public domain",
        "page": "https://commons.wikimedia.org/wiki/File:Giftun_Soraya01.JPG"
      }
    }
  ],
  "luxor": [
    {
      "slug": "karnak-temple",
      "src": "/assets/cities/luxor/01-karnak-temple.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Karnak Temple",
      "caption": "Karnak Temple",
      "credit": {
        "title": "Templo de Karnak, Luxor, Egipto, 2022-04-03, DD 144",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Templo_de_Karnak,_Luxor,_Egipto,_2022-04-03,_DD_144.jpg"
      }
    },
    {
      "slug": "luxor-temple",
      "src": "/assets/cities/luxor/02-luxor-temple.webp",
      "width": 2000,
      "height": 1319,
      "alt": "Luxor Temple",
      "caption": "Luxor Temple",
      "credit": {
        "title": "Templo de Luxor, Luxor, Egipto, 2022-04-01, DD 18",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Templo_de_Luxor,_Luxor,_Egipto,_2022-04-01,_DD_18.jpg"
      }
    },
    {
      "slug": "valley-of-kings",
      "src": "/assets/cities/luxor/03-valley-of-kings.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Valley of the Kings landscape",
      "caption": "Valley of the Kings landscape",
      "credit": {
        "title": "Luxor Valley of the Kings R01",
        "creator": "Marc Ryckaert",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Luxor_Valley_of_the_Kings_R01.jpg"
      }
    },
    {
      "slug": "valley-kings-tomb",
      "src": "/assets/cities/luxor/04-valley-kings-tomb.webp",
      "width": 2000,
      "height": 1255,
      "alt": "Valley of the Kings tomb interior",
      "caption": "Valley of the Kings tomb interior",
      "credit": {
        "title": "Tumba de Ramsés V y de Ramsés VI, Valle de las Reyes, Luxor, DD 48",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Tumba_de_Ramsés_V_y_de_Ramsés_VI,_Valle_de_las_Reyes,_Luxor,_Egipto,_2022-04-03,_DD_48.jpg"
      }
    },
    {
      "slug": "hatshepsut-temple",
      "src": "/assets/cities/luxor/05-hatshepsut-temple.webp",
      "width": 2000,
      "height": 1334,
      "alt": "Hatshepsut Temple",
      "caption": "Hatshepsut Temple",
      "credit": {
        "title": "Templo funerario de Hatshepsut, Luxor, DD 06",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Templo_funerario_de_Hatshepsut,_Luxor,_Egipto,_2022-04-03,_DD_06.jpg"
      }
    },
    {
      "slug": "medinet-habu",
      "src": "/assets/cities/luxor/06-medinet-habu.webp",
      "width": 2000,
      "height": 1226,
      "alt": "Medinet Habu Temple",
      "caption": "Medinet Habu Temple",
      "credit": {
        "title": "Medinet Habu Temple R01",
        "creator": "Marc Ryckaert (MJJR)",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Medinet_Habu_Temple_R01.jpg"
      }
    },
    {
      "slug": "colossi-memnon",
      "src": "/assets/cities/luxor/07-colossi-memnon.webp",
      "width": 2000,
      "height": 946,
      "alt": "Colossi of Memnon",
      "caption": "Colossi of Memnon",
      "credit": {
        "title": "Colosos de Memnón, Luxor, DD 131",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Colosos_de_Memnón,_Luxor,_Egipto,_2022-04-03,_DD_131.jpg"
      }
    },
    {
      "slug": "luxor-nile-sunset",
      "src": "/assets/cities/luxor/08-luxor-nile-sunset.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Nile sunset at Luxor",
      "caption": "Nile sunset at Luxor",
      "credit": {
        "title": "Luxor, Egypt, Sunset on Nile River",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Luxor,_Egypt,_Sunset_on_Nile_River.jpg"
      }
    },
    {
      "slug": "luxor-felucca",
      "src": "/assets/cities/luxor/09-luxor-felucca.webp",
      "width": 1333,
      "height": 2000,
      "alt": "Felucca on the Luxor Nile",
      "caption": "Felucca on the Luxor Nile",
      "credit": {
        "title": "Luxor Felucca",
        "creator": "Yaoshiiscool",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Luxor_Felucca.jpg"
      }
    },
    {
      "slug": "medinet-habu-entrance",
      "src": "/assets/cities/luxor/10-medinet-habu-entrance.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Medinet Habu entrance",
      "caption": "Medinet Habu entrance",
      "credit": {
        "title": "Thebes, Medinet Habu, Temple of Ramesses III, Entrance",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Thebes,_Medinet_Habu,_Egypt,_Temple_of_Ramesses_III,_Entrance.jpg"
      }
    }
  ],
  "sharm-el-sheikh": [
    {
      "slug": "divemaster-ready-to-go",
      "src": "/assets/cities/sharm-el-sheikh/01_Divemaster-ready-to-go.webp",
      "width": 1280,
      "height": 1716,
      "alt": "Diving in Sharm el-Sheikh",
      "caption": "Diving in Sharm el-Sheikh",
      "credit": {
        "title": "Divemaster-ready-to-go.jpg",
        "creator": "Charles J Sharp",
        "license": "CC BY 2.5",
        "page": "https://commons.wikimedia.org/wiki/File:Divemaster-ready-to-go.jpg"
      }
    },
    {
      "slug": "magic-of-fullmoon-between-palms",
      "src": "/assets/cities/sharm-el-sheikh/02_Magic_of_FullMoon_between_Palms.webp",
      "width": 1280,
      "height": 1379,
      "alt": "Full moon over Sharm el-Sheikh palms",
      "caption": "Full moon over Sharm el-Sheikh palms",
      "credit": {
        "title": "Magic of FullMoon between Palms.jpg",
        "creator": "NiceMan007",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Magic_of_FullMoon_between_Palms.jpg"
      }
    },
    {
      "slug": "ras-mohamed-national-park-panoramio",
      "src": "/assets/cities/sharm-el-sheikh/03_Ras_Mohamed_National_Park_-_panoramio.webp",
      "width": 1280,
      "height": 850,
      "alt": "Ras Mohamed National Park",
      "caption": "Ras Mohamed National Park",
      "credit": {
        "title": "Ras Mohamed National Park - panoramio.jpg",
        "creator": "Валерий Дед",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Ras_Mohamed_National_Park_-_panoramio.jpg"
      }
    },
    {
      "slug": "ras-mohamed-national-park-2006-panoramio",
      "src": "/assets/cities/sharm-el-sheikh/04_Ras_Mohamed_National_Park_2006_-_panoramio.webp",
      "width": 1280,
      "height": 850,
      "alt": "Ras Mohamed National Park",
      "caption": "Ras Mohamed National Park",
      "credit": {
        "title": "Ras Mohamed National Park 2006 - panoramio.jpg",
        "creator": "Валерий Дед",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Ras_Mohamed_National_Park_2006_-_panoramio.jpg"
      }
    },
    {
      "slug": "ras-mohammed-panoramio",
      "src": "/assets/cities/sharm-el-sheikh/05_Ras_Mohammed_-_panoramio.webp",
      "width": 1280,
      "height": 962,
      "alt": "Ras Mohammed",
      "caption": "Ras Mohammed",
      "credit": {
        "title": "Ras Mohammed - panoramio.jpg",
        "creator": "Ralf Houven",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Ras_Mohammed_-_panoramio.jpg"
      }
    },
    {
      "slug": "tiran-island-sharm-el-sheikh-south-sinai-egypt",
      "src": "/assets/cities/sharm-el-sheikh/06_Tiran_Island_-_Sharm_El_Sheikh_-_South_Sinai_-_Egypt.webp",
      "width": 1280,
      "height": 960,
      "alt": "Tiran Island - Sharm El Sheikh - South Sinai - Egypt",
      "caption": "Tiran Island - Sharm El Sheikh - South Sinai - Egypt",
      "credit": {
        "title": "Tiran Island - Sharm El Sheikh - South Sinai - Egypt.JPG",
        "creator": "Ahmed elkastawy",
        "license": "CC BY-SA 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Tiran_Island_-_Sharm_El_Sheikh_-_South_Sinai_-_Egypt.JPG"
      }
    },
    {
      "slug": "arrecife-de-coral-parque-nacional-ras-muhammad-egipto-2022-03-26-dd-170",
      "src": "/assets/cities/sharm-el-sheikh/07_Arrecife_de_coral_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_170.webp",
      "width": 1280,
      "height": 853,
      "alt": "Coral reef in Ras Muhammad National Park",
      "caption": "Coral reef in Ras Muhammad National Park",
      "credit": {
        "title": "Arrecife de coral, parque nacional Ras Muhammad, Egipto, 2022-03-26, DD 170.jpg",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Arrecife_de_coral,_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-26,_DD_170.jpg"
      }
    },
    {
      "slug": "arrecife-de-coral-acropora-hemprichii-xenia-umbellata-siderastrea-savignyana-par",
      "src": "/assets/cities/sharm-el-sheikh/08_Arrecife_de_coral_Acropora_hemprichii_Xenia_umbellata_Siderastrea_savignyana_par.webp",
      "width": 1280,
      "height": 853,
      "alt": "Coral reef in Ras Muhammad National Park",
      "caption": "Coral reef in Ras Muhammad National Park",
      "credit": {
        "title": "Arrecife de coral (Acropora hemprichii, Xenia umbellata, Siderastrea savignyana), parque nacional Ras Muhammad, Egipto, 2022-03-27, DD 92.jpg",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Arrecife_de_coral_(Acropora_hemprichii,_Xenia_umbellata,_Siderastrea_savignyana),_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-27,_DD_92.jpg"
      }
    },
    {
      "slug": "arrecife-de-coral-pocillopora-verrucosa-xenia-umbellata-parque-nacional-ras-muha",
      "src": "/assets/cities/sharm-el-sheikh/09_Arrecife_de_coral_Pocillopora_verrucosa_Xenia_umbellata_parque_nacional_Ras_Muha.webp",
      "width": 1280,
      "height": 1920,
      "alt": "Coral reef in Ras Muhammad National Park",
      "caption": "Coral reef in Ras Muhammad National Park",
      "credit": {
        "title": "Arrecife de coral (Pocillopora verrucosa, Xenia umbellata), parque nacional Ras Muhammad, Egipto, 2022-03-28, DD 12.jpg",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Arrecife_de_coral_(Pocillopora_verrucosa,_Xenia_umbellata),_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-28,_DD_12.jpg"
      }
    },
    {
      "slug": "coral-acropora-hemprichii-parque-nacional-ras-muhammad-egipto-2022-03-26-dd-70",
      "src": "/assets/cities/sharm-el-sheikh/10_Coral_Acropora_hemprichii_parque_nacional_Ras_Muhammad_Egipto_2022-03-26_DD_70.webp",
      "width": 1280,
      "height": 1280,
      "alt": "Coral reef in Ras Muhammad National Park",
      "caption": "Coral reef in Ras Muhammad National Park",
      "credit": {
        "title": "Coral (Acropora hemprichii), parque nacional Ras Muhammad, Egipto, 2022-03-26, DD 70.jpg",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Coral_(Acropora_hemprichii),_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-26,_DD_70.jpg"
      }
    }
  ]
};

/** Look up one image in a city by slug (feature rows / spot placements). */
export function cityImage(city: CitySlug, slug: string): CityImage {
  const found = cityMedia[city].find((i) => i.slug === slug);
  if (!found) throw new Error(`Unknown city image: ${city}/${slug}`);
  return found;
}
