/**
 * Curated theme photography for the five editorial pages (heritage / the-nile /
 * deserts / red-sea / when-to-visit) plus their on-page attribution.
 *
 * GENERATED by scripts/gen-theme-media.mjs from the Wikimedia Commons image sets
 * (scripts/convert-theme-images.mjs emits the WebP + dimensions; each set ships a
 * manifest.json with the required creator/license/source-page metadata). Do not
 * hand-edit — re-run the generator instead.
 *
 * Every image is CC-licensed or public-domain; on-page credit (creator + license
 * + Commons link) is REQUIRED and rendered by <ImageCredits>. alt/caption come
 * verbatim from each file's manifest subject/title — descriptive, never invented.
 * These English strings are shared across all locales for now (English-first);
 * lift into the i18n dictionaries when the pages are translated.
 */

export type ThemeSlug = "heritage" | "the-nile" | "deserts" | "red-sea" | "when-to-visit";

export interface ImageCredit {
  /** Title of the source work on Wikimedia Commons. */
  title: string;
  /** Attributed author/creator string, verbatim from the manifest. */
  creator: string;
  /** License short name, e.g. "CC BY 4.0", "Public domain", "CC0". */
  license: string;
  /** Canonical Commons file page (attribution target). */
  page: string;
}

export interface ThemeImage {
  /** Stable id within a theme, e.g. "giza-pyramids". */
  slug: string;
  /** Path under /public — optimized WebP. */
  src: string;
  /** Intrinsic pixel dimensions of the WebP (for next/image + masonry). */
  width: number;
  height: number;
  /** Descriptive English alt text (from manifest subject). */
  alt: string;
  /** Short English caption for gallery/credit rows. */
  caption: string;
  credit: ImageCredit;
}

export const themeMedia: Record<ThemeSlug, ThemeImage[]> = {
  "heritage": [
    {
      "slug": "giza-pyramids",
      "src": "/assets/themes/heritage/01-giza-pyramids.webp",
      "width": 2000,
      "height": 1329,
      "alt": "Giza Pyramids",
      "caption": "Giza Pyramids",
      "credit": {
        "title": "All Gizah Pyramids",
        "creator": "Ricardo Liberato",
        "license": "CC BY-SA 2.0",
        "page": "https://commons.wikimedia.org/wiki/File:All_Gizah_Pyramids.jpg"
      }
    },
    {
      "slug": "saqqara-step-pyramid",
      "src": "/assets/themes/heritage/02-saqqara-step-pyramid.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Saqqara / Step Pyramid of Djoser",
      "caption": "Saqqara / Step Pyramid of Djoser",
      "credit": {
        "title": "Pyramid of Djoser 2010",
        "creator": "Wknight94 talk",
        "license": "CC BY-SA 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Pyramid_of_Djoser_2010.jpg"
      }
    },
    {
      "slug": "karnak-temple",
      "src": "/assets/themes/heritage/03-karnak-temple.webp",
      "width": 2000,
      "height": 1500,
      "alt": "Karnak Temple",
      "caption": "Karnak Temple",
      "credit": {
        "title": "Karnak Temple Complex, Egypt73",
        "creator": "ولاء",
        "license": "Public domain",
        "page": "https://commons.wikimedia.org/wiki/File:Karnak_Temple_Complex,_Egypt73.jpg"
      }
    },
    {
      "slug": "luxor-temple",
      "src": "/assets/themes/heritage/04-luxor-temple.webp",
      "width": 2000,
      "height": 1205,
      "alt": "Luxor Temple",
      "caption": "Luxor Temple",
      "credit": {
        "title": "Luxor Temple R04",
        "creator": "Marc Ryckaert",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Luxor_Temple_R04.jpg"
      }
    },
    {
      "slug": "abu-simbel",
      "src": "/assets/themes/heritage/05-abu-simbel.webp",
      "width": 2000,
      "height": 1058,
      "alt": "Abu Simbel",
      "caption": "Abu Simbel",
      "credit": {
        "title": "Templo de Ramsés II, Abu Simbel",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Templo_de_Ramsés_II,_Abu_Simbel,_Egipto,_2022-04-02,_DD_03.jpg"
      }
    },
    {
      "slug": "philae-temple",
      "src": "/assets/themes/heritage/06-philae-temple.webp",
      "width": 2000,
      "height": 1453,
      "alt": "Philae Temple",
      "caption": "Philae Temple",
      "credit": {
        "title": "Philae Temple R01",
        "creator": "Marc Ryckaert",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Philae_Temple_R01.jpg"
      }
    },
    {
      "slug": "kom-ombo",
      "src": "/assets/themes/heritage/07-kom-ombo.webp",
      "width": 2000,
      "height": 1499,
      "alt": "Kom Ombo Temple",
      "caption": "Kom Ombo Temple",
      "credit": {
        "title": "Kom Ombo 30",
        "creator": "Olaf Tausch",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Kom_Ombo_30.jpg"
      }
    },
    {
      "slug": "coptic-cairo",
      "src": "/assets/themes/heritage/08-coptic-cairo.webp",
      "width": 2000,
      "height": 790,
      "alt": "Coptic Cairo",
      "caption": "Coptic Cairo",
      "credit": {
        "title": "Coptic Cairo 2022 10",
        "creator": "Onceinawhile",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Coptic_Cairo_2022_10.jpg"
      }
    },
    {
      "slug": "islamic-cairo",
      "src": "/assets/themes/heritage/09-islamic-cairo.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Islamic Cairo",
      "caption": "Islamic Cairo",
      "credit": {
        "title": "Cairo, Islamic Cairo, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Cairo,_Islamic_Cairo,_Egypt.jpg"
      }
    },
    {
      "slug": "nile-aswan",
      "src": "/assets/themes/heritage/10-nile-aswan.webp",
      "width": 2000,
      "height": 1386,
      "alt": "Nile Valley / Aswan",
      "caption": "Nile Valley / Aswan",
      "credit": {
        "title": "Aswan, Landscape, photo 1 of 9",
        "creator": "Antonio Beato",
        "license": "CC0",
        "page": "https://commons.wikimedia.org/wiki/File:Aswan,_Landscape,_Pictures,_1870-1888,_photo_1_of_9_-_Archivio_fotografico_Museo_Egizio,_Turin_INV33_005.jpg"
      }
    }
  ],
  "the-nile": [
    {
      "slug": "nile-riverbank-kom-ombo-edfu",
      "src": "/assets/themes/the-nile/01-nile-riverbank-kom-ombo-edfu.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Nile riverbank between Kom Ombo and Edfu",
      "caption": "Nile riverbank between Kom Ombo and Edfu",
      "credit": {
        "title": "Nile riverbank between Kom Ombo and Edfu temples",
        "creator": "Gildas Guionnet",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nile_riverbank_between_Kom_Ombo_and_Edfu_temples.jpg"
      }
    },
    {
      "slug": "luxor-boats-on-nile",
      "src": "/assets/themes/the-nile/02-luxor-boats-on-nile.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Boats and river life in Luxor",
      "caption": "Boats and river life in Luxor",
      "credit": {
        "title": "Luxor, Egypt, Boats on Nile River",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Luxor,_Egypt,_Boats_on_Nile_River.jpg"
      }
    },
    {
      "slug": "aswan-feluccas",
      "src": "/assets/themes/the-nile/03-aswan-feluccas.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Feluccas on the Nile at Aswan",
      "caption": "Feluccas on the Nile at Aswan",
      "credit": {
        "title": "Nile River, Boats and feluccas, Aswan, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nile_River,_Boats_and_feluccas,_Aswan,_Egypt.jpg"
      }
    },
    {
      "slug": "aswan-boat-egrets",
      "src": "/assets/themes/the-nile/04-aswan-boat-egrets.webp",
      "width": 1333,
      "height": 2000,
      "alt": "Wildlife and traditional boat on the Nile",
      "caption": "Wildlife and traditional boat on the Nile",
      "credit": {
        "title": "Cattle Egrets near a traditional boat on the Nile River in Aswan, Egypt",
        "creator": "Mohamed Suttra",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Cattle_Egrets_near_a_traditional_boat_on_the_Nile_River_in_Aswan,_Egypt.jpg"
      }
    },
    {
      "slug": "elephantine-island",
      "src": "/assets/themes/the-nile/05-elephantine-island.webp",
      "width": 2000,
      "height": 1328,
      "alt": "Elephantine Island, Aswan",
      "caption": "Elephantine Island, Aswan",
      "credit": {
        "title": "Aswan Elephantine Island R02",
        "creator": "Marc Ryckaert",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Aswan_Elephantine_Island_R02.jpg"
      }
    },
    {
      "slug": "aswan-wide-nile",
      "src": "/assets/themes/the-nile/06-aswan-wide-nile.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Wide Nile view at Aswan",
      "caption": "Wide Nile view at Aswan",
      "credit": {
        "title": "Nile River, Aswan, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nile_River,_Aswan,_Egypt.jpg"
      }
    },
    {
      "slug": "cairo-nile-skyline-sunset",
      "src": "/assets/themes/the-nile/07-cairo-nile-skyline-sunset.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Cairo and the Nile at sunset",
      "caption": "Cairo and the Nile at sunset",
      "credit": {
        "title": "Cairo, Nile River, Residential buildings at sunset, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Cairo,_Nile_River,_Residential_buildings_at_sunset,_Egypt.jpg"
      }
    },
    {
      "slug": "cairo-nile-night",
      "src": "/assets/themes/the-nile/08-cairo-nile-night.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Cairo’s Nile at night",
      "caption": "Cairo’s Nile at night",
      "credit": {
        "title": "Egypt, Night Cairo and river Nile, Zamalek city lights",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Egypt,_Night_Cairo_and_river_Nile,_Zamalek_city_lights.jpg"
      }
    },
    {
      "slug": "river-nile-near-aswan",
      "src": "/assets/themes/the-nile/09-river-nile-near-aswan.webp",
      "width": 2000,
      "height": 1328,
      "alt": "Nile landscape near Aswan",
      "caption": "Nile landscape near Aswan",
      "credit": {
        "title": "River Nile near Aswan Egypt - panoramio",
        "creator": "David Broad",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:River_Nile_near_Aswan_Egypt_-_panoramio.jpg"
      }
    },
    {
      "slug": "nile-felucca-aswan",
      "src": "/assets/themes/the-nile/10-nile-felucca-aswan.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Single felucca on the Nile",
      "caption": "Single felucca on the Nile",
      "credit": {
        "title": "Nile River, Felucca boat, Aswan, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nile_River,_Felucca_boat,_Aswan,_Egypt.jpg"
      }
    }
  ],
  "deserts": [
    {
      "slug": "white-desert-alien-landscape",
      "src": "/assets/themes/deserts/01-white-desert-alien-landscape.webp",
      "width": 2000,
      "height": 1333,
      "alt": "White Desert / surreal rock formations",
      "caption": "White Desert / surreal rock formations",
      "credit": {
        "title": "White Desert, Alien landscape, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:White_Desert,_Alien_landscape,_Egypt.jpg"
      }
    },
    {
      "slug": "black-desert-panorama",
      "src": "/assets/themes/deserts/02-black-desert-panorama.webp",
      "width": 2000,
      "height": 446,
      "alt": "Black Desert panorama",
      "caption": "Black Desert panorama",
      "credit": {
        "title": "Black Desert, Egypt 08",
        "creator": "Viktor Lazić",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Black_Desert,_Egypt_08.jpg"
      }
    },
    {
      "slug": "bahariya-oasis",
      "src": "/assets/themes/deserts/03-bahariya-oasis.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Bahariya Oasis",
      "caption": "Bahariya Oasis",
      "credit": {
        "title": "Bahariya Oasis in Egypt",
        "creator": "Ahmedherz",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Bahariya_Oasis_in_Egypt.jpg"
      }
    },
    {
      "slug": "siwa-oracle-temple",
      "src": "/assets/themes/deserts/04-siwa-oracle-temple.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Siwa Oasis / Oracle of Amun",
      "caption": "Siwa Oasis / Oracle of Amun",
      "credit": {
        "title": "Siwa Oasis, Temple of the Oracle of Amun, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Siwa_Oasis,_Temple_of_the_Oracle_of_Amun,_Egypt.jpg"
      }
    },
    {
      "slug": "fayoum-desert",
      "src": "/assets/themes/deserts/05-fayoum-desert.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Fayoum desert landscape",
      "caption": "Fayoum desert landscape",
      "credit": {
        "title": "Fayoum desert",
        "creator": "Elaaf Selim",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Fayoum_desert.jpg"
      }
    },
    {
      "slug": "sinai-canyon",
      "src": "/assets/themes/deserts/06-sinai-canyon.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Sinai canyon and mountain landscape",
      "caption": "Sinai canyon and mountain landscape",
      "credit": {
        "title": "Sinai, Egypt, Canyon through the mountains, majestic desert landscape",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Sinai,_Egypt,_Canyon_through_the_mountains,_majestic_desert_landscape.jpg"
      }
    },
    {
      "slug": "nuweiba-desert-road",
      "src": "/assets/themes/deserts/07-nuweiba-desert-road.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Sinai desert road / Nuweiba",
      "caption": "Sinai desert road / Nuweiba",
      "credit": {
        "title": "Nuweiba, Desert road, Sinai, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nuweiba,_Desert_road,_Sinai,_Egypt.jpg"
      }
    },
    {
      "slug": "wadi-el-hitan-fennec",
      "src": "/assets/themes/deserts/08-wadi-el-hitan-fennec.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Wadi El Hitan / desert wildlife",
      "caption": "Wadi El Hitan / desert wildlife",
      "credit": {
        "title": "Fennec FOX - Valley of the Whales - Wadi al Hitan 2",
        "creator": "Khaled Mokhtar",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Fennec_FOX_-_Valley_of_the_Whales_-_Wadi_al_Hitan_2.jpg"
      }
    },
    {
      "slug": "red-sea-mountains",
      "src": "/assets/themes/deserts/09-red-sea-mountains.webp",
      "width": 2000,
      "height": 1339,
      "alt": "Red Sea Mountains",
      "caption": "Red Sea Mountains",
      "credit": {
        "title": "Red Sea Mountains, Egypt (3280314450)",
        "creator": "Andrew A. Shenouda",
        "license": "CC BY 2.0",
        "page": "https://commons.wikimedia.org/wiki/File:Red_Sea_Mountains,_Egypt_(3280314450).jpg"
      }
    },
    {
      "slug": "saint-catherine-monastery",
      "src": "/assets/themes/deserts/10-saint-catherine-monastery.webp",
      "width": 2000,
      "height": 1233,
      "alt": "Saint Catherine’s Monastery and Sinai mountains",
      "caption": "Saint Catherine’s Monastery and Sinai mountains",
      "credit": {
        "title": "Saint Catherine's Monastery in Sinai surrounded by mountains (FL45952482)",
        "creator": "IPPA photographer",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Saint_Catherine's_Monastery_in_Sinai_surrounded_by_mountains_mentioned_in_the_Bible_when_the_People_of_Israel_left_Egypt_(FL45952482).jpg"
      }
    }
  ],
  "red-sea": [
    {
      "slug": "coral-reef-public-domain",
      "src": "/assets/themes/red-sea/01-coral-reef-public-domain.webp",
      "width": 2000,
      "height": 1500,
      "alt": "Red Sea coral reef",
      "caption": "Red Sea coral reef",
      "credit": {
        "title": "Coral Reef in the Red Sea",
        "creator": "Mahmoud Habeeb",
        "license": "Public domain",
        "page": "https://commons.wikimedia.org/wiki/File:Coral_Reef_in_the_Red_Sea.JPG"
      }
    },
    {
      "slug": "sharm-coral",
      "src": "/assets/themes/red-sea/02-sharm-coral.webp",
      "width": 2000,
      "height": 2000,
      "alt": "Sharm el-Sheikh coral reef",
      "caption": "Sharm el-Sheikh coral reef",
      "credit": {
        "title": "Coral (Acropora hemprichii), Ras Katy, Sharm el-Sheij",
        "creator": "Diego Delso",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Coral_(Acropora_hemprichii),_Ras_Katy,_Sharm_el-Sheij,_Egipto,_2022-03-26,_DD_108.jpg"
      }
    },
    {
      "slug": "hurghada-coast",
      "src": "/assets/themes/red-sea/03-hurghada-coast.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Hurghada coast",
      "caption": "Hurghada coast",
      "credit": {
        "title": "Hurghada, Qesm Hurghada, Red Sea Governorate (29)",
        "creator": "Almondox",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Hurghada,_Qesm_Hurghada,_Red_Sea_Governorate,_Egypt_-_panoramio_(29).jpg"
      }
    },
    {
      "slug": "marsa-alam",
      "src": "/assets/themes/red-sea/04-marsa-alam.webp",
      "width": 2000,
      "height": 1334,
      "alt": "Marsa Alam coast",
      "caption": "Marsa Alam coast",
      "credit": {
        "title": "Marsa Alam R02",
        "creator": "Marc Ryckaert (MJJR)",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Marsa_Alam_R02.jpg"
      }
    },
    {
      "slug": "dahab-panorama",
      "src": "/assets/themes/red-sea/05-dahab-panorama.webp",
      "width": 2000,
      "height": 751,
      "alt": "Dahab coastline panorama",
      "caption": "Dahab coastline panorama",
      "credit": {
        "title": "Dahab (Blue Whole)",
        "creator": "Petar Milošević",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Dahab_(Blue_Whole).jpg"
      }
    },
    {
      "slug": "shadwan-island",
      "src": "/assets/themes/red-sea/06-shadwan-island.webp",
      "width": 2000,
      "height": 1500,
      "alt": "Red Sea island landscape",
      "caption": "Red Sea island landscape",
      "credit": {
        "title": "Shadwan Island",
        "creator": "Wusel007",
        "license": "CC BY-SA 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Shadwan_Island.JPG"
      }
    },
    {
      "slug": "nuweiba-red-sea-mountains",
      "src": "/assets/themes/red-sea/07-nuweiba-red-sea-mountains.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Nuweiba mountains and sea",
      "caption": "Nuweiba mountains and sea",
      "credit": {
        "title": "Nuweiba, Mountains, Red Sea, Sinai",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nuweiba,_Mountains,_Red_Sea,_Sinai,_Egypt.jpg"
      }
    },
    {
      "slug": "red-sea-mountains",
      "src": "/assets/themes/red-sea/08-red-sea-mountains.webp",
      "width": 2000,
      "height": 1339,
      "alt": "Red Sea mountain coast",
      "caption": "Red Sea mountain coast",
      "credit": {
        "title": "Red Sea Mountains, Egypt",
        "creator": "Andrew A. Shenouda",
        "license": "CC BY 2.0",
        "page": "https://commons.wikimedia.org/wiki/File:Red_Sea_Mountains,_Egypt_(3280314450).jpg"
      }
    },
    {
      "slug": "dahab-paradise",
      "src": "/assets/themes/red-sea/09-dahab-paradise.webp",
      "width": 2000,
      "height": 1000,
      "alt": "Dahab coastline panorama",
      "caption": "Dahab coastline panorama",
      "credit": {
        "title": "Dahab, Egypt",
        "creator": "Dr. Ondřej Havelka (cestovatel)",
        "license": "CC BY-SA 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Dahab,_Egypt.jpg"
      }
    },
    {
      "slug": "coral-bay-sharm",
      "src": "/assets/themes/red-sea/10-coral-bay-sharm.webp",
      "width": 2000,
      "height": 852,
      "alt": "Sharm El Sheikh coastal bay",
      "caption": "Sharm El Sheikh coastal bay",
      "credit": {
        "title": "Coral Bay, Sharm-El-Sheikh",
        "creator": "74papa",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Coral_Bay,_Sharm-El-Sheikh.jpg"
      }
    }
  ],
  "when-to-visit": [
    {
      "slug": "nile-at-sunset",
      "src": "/assets/themes/when-to-visit/01-nile-at-sunset.webp",
      "width": 2000,
      "height": 1335,
      "alt": "Nile River at sunset",
      "caption": "Nile River at sunset",
      "credit": {
        "title": "Egypt - Nile at sunset",
        "creator": "Rab Lawrence",
        "license": "CC BY 2.0",
        "page": "https://commons.wikimedia.org/wiki/File:Egypt_-_Nile_at_sunset.jpg"
      }
    },
    {
      "slug": "siwa-cleopatras-bath",
      "src": "/assets/themes/when-to-visit/02-siwa-cleopatras-bath.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Siwa Oasis / Cleopatra’s Bath",
      "caption": "Siwa Oasis / Cleopatra’s Bath",
      "credit": {
        "title": "Siwa Oasis, Cleopatra's Bath, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Siwa_Oasis,_Cleopatra's_Bath,_Egypt.jpg"
      }
    },
    {
      "slug": "white-desert-rock",
      "src": "/assets/themes/when-to-visit/03-white-desert-rock.webp",
      "width": 2000,
      "height": 1333,
      "alt": "White Desert rock formations",
      "caption": "White Desert rock formations",
      "credit": {
        "title": "White Desert, Rock formation, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:White_Desert,_Rock_formation,_Egypt.jpg"
      }
    },
    {
      "slug": "red-sea-soma-bay",
      "src": "/assets/themes/when-to-visit/04-red-sea-soma-bay.webp",
      "width": 1333,
      "height": 2000,
      "alt": "Red Sea coast / Soma Bay",
      "caption": "Red Sea coast / Soma Bay",
      "credit": {
        "title": "Red Sea coast of Soma Bay, Egypt",
        "creator": "dronepicr",
        "license": "CC BY 2.0",
        "page": "https://commons.wikimedia.org/wiki/File:Red_Sea_coast_of_Soma_Bay,_Egypt_(51224128355).jpg"
      }
    },
    {
      "slug": "alexandria-beach",
      "src": "/assets/themes/when-to-visit/05-alexandria-beach.webp",
      "width": 2000,
      "height": 933,
      "alt": "Mediterranean coast / Alexandria",
      "caption": "Mediterranean coast / Alexandria",
      "credit": {
        "title": "Alexandria Beach",
        "creator": "Faris El-Gwely",
        "license": "CC BY-SA 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Alexandria_Beach.JPG"
      }
    },
    {
      "slug": "sinai-sunrise",
      "src": "/assets/themes/when-to-visit/06-sinai-sunrise.webp",
      "width": 2000,
      "height": 1500,
      "alt": "Sinai Mountains at sunrise",
      "caption": "Sinai Mountains at sunrise",
      "credit": {
        "title": "'SUNRISE' over Mt Sinai Mountains(Egypt)",
        "creator": "Rudolph.A.furtado",
        "license": "Public domain",
        "page": "https://commons.wikimedia.org/wiki/File:'SUNRISE'_over_Mt_Sinai_Mountains(Egypt).JPG"
      }
    },
    {
      "slug": "dakhla-sand-dunes",
      "src": "/assets/themes/when-to-visit/07-dakhla-sand-dunes.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Dakhla Oasis / Sahara dunes",
      "caption": "Dakhla Oasis / Sahara dunes",
      "credit": {
        "title": "Sand dunes, Libyan Desert, Dakhla Oasis, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Sand_dunes,_Libyan_Desert,_Dakhla_Oasis,_Egypt.jpg"
      }
    },
    {
      "slug": "aswan-nile",
      "src": "/assets/themes/when-to-visit/08-aswan-nile.webp",
      "width": 2000,
      "height": 1328,
      "alt": "Aswan / Nile Valley",
      "caption": "Aswan / Nile Valley",
      "credit": {
        "title": "Aswan Nile R05",
        "creator": "Marc Ryckaert (MJJR)",
        "license": "CC BY 3.0",
        "page": "https://commons.wikimedia.org/wiki/File:Aswan_Nile_R05.jpg"
      }
    },
    {
      "slug": "nuweiba-mountains",
      "src": "/assets/themes/when-to-visit/09-nuweiba-mountains.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Nuweiba / Sinai mountains and Red Sea",
      "caption": "Nuweiba / Sinai mountains and Red Sea",
      "credit": {
        "title": "Nuweiba, Mountains, Red Sea, Sinai, Egypt",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Nuweiba,_Mountains,_Red_Sea,_Sinai,_Egypt.jpg"
      }
    },
    {
      "slug": "luxor-nile-sunset",
      "src": "/assets/themes/when-to-visit/10-luxor-nile-sunset.webp",
      "width": 2000,
      "height": 1333,
      "alt": "Luxor / Nile sunset",
      "caption": "Luxor / Nile sunset",
      "credit": {
        "title": "Luxor, Egypt, River Nile sunset",
        "creator": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "page": "https://commons.wikimedia.org/wiki/File:Luxor,_Egypt,_River_Nile_sunset.jpg"
      }
    }
  ]
};

/** Look up one image in a theme by slug (feature rows / spot placements). */
export function themeImage(theme: ThemeSlug, slug: string): ThemeImage {
  const found = themeMedia[theme].find((i) => i.slug === slug);
  if (!found) throw new Error(`Unknown theme image: ${theme}/${slug}`);
  return found;
}
